### ISSUE TITLE
Log context works fine in query builder, but does not work when switching to SQL Editor

### ISSUE THREAD

**Issue by 692568516** [grafana/clickhouse-datasource#1028]
query builder
![Image](https://github.com/user-attachments/assets/6e81f56a-0bc5-405b-80a8-a2d40344379a)

sql editor
![Image](https://github.com/user-attachments/assets/0d615fb1-9432-450e-a8f6-00c24c44d0bb)

**Comment by SpencerTorres** [comment]
This is a known limitation. Builder queries can be easily manipulated and re-structured, but SQL queries are very complex. It's hard to find a generalized solution for manipulating a SQL query. The module we use for converting a SQL query to an AST does not always work with ClickHouse SQL. I have some ideas on how to do this and plan on adding it in a future PR.

We don't have an open issue for this as a feature request, so if you want to you can submit a new issue requesting this feature specifically. We can suggest ideas and discuss implementation there. I'll close this issue for now though.

Thanks!
