### ISSUE TITLE
Support expression in time field for timeseries

### ISSUE THREAD

**Issue by gingerwizard** [grafana/clickhouse-datasource#107]
**Is your feature request related to a problem? Please describe.**

Currently if you using the TimeSeries component of the query builder, the user is forced to select a time field. Its not uncommon for users to a time field encoded in a different type e.g. int. ClickHouse supports expressions to allow conversion if required.

**Describe the solution you'd like**=

Please allow free typing of an expression in the Timefield input or allow switching to an expression mode.

**Additional context**

![image](https://user-images.githubusercontent.com/12695796/157660424-54cec2bb-4ab4-4505-b9bc-9deecdbe6d22.png)

This needs alittle care since ther time field is used in the `WHERE` clause e.g. `$__timeFilter(created_at)` - this should probably use the alias `time` or id expect issues on some expressions.

**Comment by SpencerTorres** [comment]
This is now possible in [v4](https://github.com/grafana/clickhouse-datasource/releases)

The `$__timeInterval` macro is still added when in `Time Series Aggregate` mode, but the query still functions as expected. `time` alias is also handled in the query. If the user wanted to exclude this macro they could use `Table Aggregate` mode. 

![image](https://github.com/grafana/clickhouse-datasource/assets/28887171/314ae2a1-f21a-466c-b49a-807a281742ad)
