### ISSUE TITLE
Allow use of `$__timeFilter` in queries for variables

### ISSUE THREAD

**Issue by vincentbernat** [grafana/clickhouse-datasource#113]
**Is your feature request related to a problem? Please describe.**
On some backends, we can use `$__timeFilter` in a query defining a variable. This does not seem possible when using Clickhouse as a datasource.

**Describe the solution you'd like**
I would like to be able to define a variable with:
```sql
SELECT DISTINCT SamplerName
FROM flows
WHERE $__timeFilter(TimeReceived)
```
Currently, this generates a `TimeReceived >= 0 AND TimeReceived < 0` query.

**Comment by scottlepp** [comment]
Hi @vincentbernat.

What version of Grafana?
What version of the plugin?

What is your time range?  I have it set to Last 6 hours and I'm seeing this generated from the macro with your query example:
```
SELECT DISTINCT SamplerName
FROM flows
WHERE TimeReceived >= '1648118196' AND TimeReceived <= '1648139796'
```
