### ISSUE TITLE
RE clause clashes with Clickhouse `format` function

### ISSUE THREAD

**Issue by up-to-you** [grafana/clickhouse-datasource#116]
**Describe the bug**
RE clause clashes with Clickhouse `format` function

**Versions**
Grafana and Plugin versions: MOST LATEST

**Query**
A text example of the query ( if possible ):

select format('[{0}] {1}', 1, 2);

sends to the server:

SELECT FORMAT ('[{0}] {1}', 1, 2)

and Clickhouse suitably responds:

error querying the database: code: 46, message: Unknown function FORMAT. Maybe you meant: ['format']

**Comment by up-to-you** [comment]
Workaround is to use `concat` Clickhouse function.

**Comment by bossinc** [comment]
requires #131
