### ISSUE TITLE
Case sensitive database with adhoc filter

### ISSUE THREAD

**Issue by dsztykman** [grafana/clickhouse-datasource#117]
**Describe the bug**
When specifying database using variable `clickhouse_adhoc_query` the request to clickhouse is in uppercase when the variable value is in lower case.

**Versions**
Grafana version 8.4.4
Plugin version 1.1.2

**Query**
This generate the following query:
```SELECT name , type , table FROM system.columns WHERE database IN ('SAMPLE') AND table = 'cts'```

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'settings'
3. Add a new adhocfilter
4. Add a new constant variable `clickhouse_adhoc_query` with the value `database.table`
6. See the query generated by the adhoc filter is `DATABASE`

**Expected behavior**
The Adhoc filter should use the case from the value.
So for a value of `database.table` the query should be:
```SELECT name , type , table FROM system.columns WHERE database IN ('database') AND table = 'table'```

**Screenshots**

![Screenshot 2022-03-28 at 10 47 01](https://user-images.githubusercontent.com/33227713/160363106-71120a7c-9149-4a5f-947a-deaafc664965.png)

**Comment by dsztykman** [comment]
After playing a bit more whenever I use any filter  in the dashboard (a query or an adhoc filter) it switches every chart  into upper case for the table.

**Comment by bossinc** [comment]
@dsztykman I am not sure what is being switched to uppercase. Is SQL sent to the server switched to uppercase? If so, will you provide before and after examples? 😃 
We are switching keywords to uppercase, but values and variables should not be affected.

**Comment by dsztykman** [comment]
https://user-images.githubusercontent.com/33227713/160681963-ed879cfd-535f-4d3b-bedb-4108b14f72fa.mov

@bossinc here's the demo of the issue, basically after adding an adhoc filter the query switch from: 
```SELECT toStartOfInterval(toDateTime(timestamp), INTERVAL 30 second) as time,  count(*) FROM sample.cts WHERE timestamp >= '1648535440' AND timestamp <= '1648578640' GROUP BY time ORDER BY time ASC```
To
```SELECT toStartOfInterval(toDateTime(timestamp), INTERVAL 30 second) as time,  count(*) FROM SAMPLE .cts WHERE timestamp >= '1648535440' AND timestamp <= '1648578640' GROUP BY time ORDER BY time ASC```

**Comment by dsztykman** [comment]
The same happens when I add a "simple" filter it's not specific to adhoc

**Comment by blinkov** [comment]
As a hypothesis, this could be triggered because `sample` is a keyword https://clickhouse.com/docs/en/sql-reference/statements/select/sample/ and the plug-in couldn't understand that it's used in the context where a database name is expected.

**Comment by bossinc** [comment]
@dsztykman thank you! I believe @blinkov is correct. I am working on a fix.

**Comment by bossinc** [comment]
requires #131
