### ISSUE TITLE
Wrong sql format in statement WITH FILL STEP

### ISSUE THREAD

**Issue by ocean-404** [grafana/clickhouse-datasource#121]
**Describe the bug**
In SQL editor,  "WITH FILL STEP" will be move to the beginning of final query.

**Versions**
Grafana v7.3.0
ClickHouse 1.0.1

**Query**
SELECT
    $__timeInterval(datetime) as time,
    quantile(0.50)(int_value) as "p50"
FROM "primitives"
WHERE 
    topic = '$topic' AND
    $__timeFilter(datetime)
GROUP BY time
ORDER BY time ASC WITH FILL STEP 30

**To Reproduce**
1. Go to SQL editor
2. order by ... with fill step
3. run query
4. check the query in query inspector

**Expected behavior**
wrong sql in query inspector

**Screenshots**
![image](https://user-images.githubusercontent.com/85693440/161999666-a3ba7e24-0b54-454a-bf22-712af181cb8c.png)

**Comment by bossinc** [comment]
requires #131
