### ISSUE TITLE
Support Clickhouse HTTP Interface

### ISSUE THREAD

**Issue by derN3rd** [grafana/clickhouse-datasource#126]
Currently this clickhouse datasource uses the native Clickhouse TCP interface which works very well.
But this limits the usage to only the official clickhouse server connection, which excludes middlewares like [CHProxy](https://github.com/ContentSquare/chproxy).

We use CHProxy for caching, permission handling and other metric related logging, which is not possible with this datasource.

Are there any plans for this?
Thanks in advance

**Comment by gingerwizard** [comment]
This is a driver issue. The current go driver uses native - but we have plans to expand HTTP support at this layer. This isn't a trivial effort however but its noted as important.

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/clickhouse-go/issues/597

**Comment by gingerwizard** [comment]
@bossinc assign to me

**Comment by Relect** [comment]
why you can't use the one implemented in clickhouse
https://clickhouse.com/docs/en/interfaces/http/ ?

**Comment by gingerwizard** [comment]
@derN3rd PR is up
