### ISSUE TITLE
AST parser 2.0

### ISSUE THREAD

**Issue by bossinc** [grafana/clickhouse-datasource#131]
Use `EXPLAIN AST` to create an AST in Grafana. Our current AST solution is having problems with building the same AST as ClickHouse. Using `EXPLAIN AST` will hopefully eliminate any discrepancies in generating the Grafana AST.

We need an AST for removing conditional alls and ad-hoc filters.

We plan on injecting/removing where clauses based on ad-hoc filters/removing conditional alls. Next, we will walk through the AST to build the new SQL statement.

The results of EXPLAIN AST:
`SELECT * FROM table WHERE date >= today`
```
  SelectQuery (children 3)
   ExpressionList (children 1)
    Asterisk
   TablesInSelectQuery (children 1)
    TablesInSelectQueryElement (children 1)
     TableExpression (children 1)
      TableIdentifier table
   Function greaterOrEquals (children 1)
    ExpressionList (children 2)
     Identifier date
     Identifier today
 Identifier TabSeparatedWithNamesAndTypes
```

**Comment by gingerwizard** [comment]
@bossinc we will use https://github.com/ClickHouse/ClickHouse/issues/37918

**Comment by gingerwizard** [comment]
https://github.com/ClickHouse/ClickHouse/issues/38263 also relevant
