### ISSUE TITLE
rebuild plugin

### ISSUE THREAD

**Issue by Relect** [grafana/clickhouse-datasource#136]
Manual for build plugin grafana very uncomfortable
https://grafana.com/tutorials/build-a-panel-plugin/

default directory for linux  is absent (most likely /var/lib/grafana/plugins)
https://grafana.com/docs/grafana/next/setup-grafana/configure-grafana/#plugins

"yarn dev" create folder "dist" -  what to do with her?
I'm add folder dist to /var/lib/grafana/plugins
and  _systemct restart grafana-server_
plugin not add.

As a result, testing the slightest change in the repository becomes very difficult.

**Comment by gingerwizard** [comment]
This isn't a ticket for this plugin but rather a general grafana issue.
