### ISSUE TITLE
Data with long days time range is not able loaded in grafana v8.0+ dashboard when using Clickhouse plugins with v1.1.2.

### ISSUE THREAD

**Issue by sujuanliu** [grafana/clickhouse-datasource#140]
**What happened**:
Grafana: v9.0.0,v8.5.4, v8.3.3
ClickHouse Plugin: v1.1.2

When using ClickHouse plugin with version 1.1.2, 7 days' data in dashboard is not able loaded as expected. But data with short time range is loaded correctly in dashboard. e.g. 24 hours, 1-6hours

**What you expected to happen**: 
7 days's data should be shown correctly in dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install ClickHouse with latest version 1.1.2.
2. Create a dashboard with ClickHouse as datasource.
3. Select time ranage as 30 mins,1 or 6 hours. You will find the data is shown well.
4. Select time range as 2 days or 7 days, you will find  the msg "driver: bad connection: Could not process SQL results" is shown in dashboard. Actually, the SQL executed in ClickHouse takes only 10 seconds or less in the ClickHouse server.

**Anything else we need to know?**:
The issue only occurs when installing ClickHouse plugins with lastest version 1.1.2. If you downgrade to version 1.0.1, the data is shown correctly in dashboard.  There are 2000 million data for 7 days in ClickHouse, and it returns 1900+ rows when executing the SQL.

**Environment**:
- Grafana version: 9.0.0, 8.5.4, 8.3.3
- Data source type & version: ClickHouse Plugin version v1.1.2
- OS Grafana is installed on: CentOS 7
- User OS & Browser: MacOS, Chrome
- Grafana plugins: ClickHouse Plugin version v1.1.2
- Others:

**Comment by gingerwizard** [comment]
e.g.
![image](https://user-images.githubusercontent.com/12695796/174822490-acfcd692-4e62-451e-938c-369a1bdc687a.png)

using play

![image](https://user-images.githubusercontent.com/12695796/174822751-ec5c0fd8-e614-4b1b-b002-ecb1e4ffed70.png)

```
SELECT
        toStartOfMonth(created_at) AS time,
                lower(repo_name) AS repo,
        count() AS c
    FROM github_events
    WHERE (event_type = 'WatchEvent') AND (toYear(created_at) >= 2015) AND (repo IN
    (
        SELECT lower(repo_name) AS repo
        FROM github_events
        WHERE (event_type = 'WatchEvent') AND (toYear(created_at) >= 2015)
        GROUP BY repo
        ORDER BY count() DESC
        LIMIT 10
    ))
    GROUP BY
        repo,
        time
    ORDER BY time ASC    
```

**Comment by sujuanliu** [comment]
@gingerwizard i tried to configure the datasource as a higher value 3600 s, but got the same timeout error when showing 7 days' data. It doesn't looks like the issue is related to datasource timeout config because the data is still able to show when it takes more than 10s or even serveral minutes in plugin with version 1.0.1.

i use ClickHouse to store Nginx access logs and monitor the domain request count via grafana. Below is the SQL i used in grafana.

SELECT $__timeInterval(create_time) as time, create_time, fields_log_source, count(1) as "domain_name:" FROM huoli.nginx_log_all WHERE $__timeFilter(create_time) AND (fields_log_source in($domain_name) ) GROUP BY create_time, fields_log_source, time ORDER BY time ASC

![image](https://user-images.githubusercontent.com/20679929/174921406-2d503c30-a827-411a-b8a9-cf2ec63c2741.png)

It is OK for showing data in 24 hours：
![image](https://user-images.githubusercontent.com/20679929/174921964-adfc50e3-d50c-44fd-9e00-168241e73723.png)

![image](https://user-images.githubusercontent.com/20679929/174921635-45a61f8b-ade8-4783-ba14-87514033269a.png)

Data is now showing in 7 days：
![image](https://user-images.githubusercontent.com/20679929/174921727-d5a938a9-a958-4348-be17-de3009cebe67.png)

![image](https://user-images.githubusercontent.com/20679929/174921767-513b5bf0-bb5e-4a21-b5a4-6a16482ce0d3.png)

**Comment by sujuanliu** [comment]
Here is the graph for 7 days when using clickhouse plugin with version 1.0.1.

![image](https://user-images.githubusercontent.com/20679929/174924647-553e7f75-a8d9-4c3c-85c6-96247247fb39.png)

![image](https://user-images.githubusercontent.com/20679929/174924686-6b80762c-2c1f-47f9-86eb-1e38f479f6d8.png)

**Comment by gingerwizard** [comment]
@sujuanliu we will try to release this week so you can test. v2 of the driver is a significant improvement and this looks like a driver issue in v1.

**Comment by sujuanliu** [comment]
I haven't seen the release of v2 yet. I will wait for the realse and test it. Thanks!

**Comment by washcroft** [comment]
@sujuanliu
**Here's a ZIP containing a built latest version (as of now):**
https://github.com/4thu/clickhouse-datasource/raw/main/grafana-clickhouse-datasource.zip

To build your own, follow the [Grafana instructions](https://grafana.com/tutorials/build-a-data-source-backend-plugin/):

Clone/download repo

```
cd clickhouse-datasource
yarn install
yarn build
go get -u github.com/grafana/grafana-plugin-sdk-go
go mod tidy
mage -v
```

Now, rename the new dist folder grafana-clickhouse-datasource, and ZIP it up (so that the grafana-clickhouse-datasource folder is in the ZIP).

Finally, follow the [Grafana instructions](https://grafana.com/docs/grafana/latest/administration/plugin-management/) for installing a plugin from ZIP, remember to add **grafana-clickhouse-datasource** to the allowed list of unsigned plugins.

**Comment by gingerwizard** [comment]
@sujuanliu release 2.0-beta out. Please try.

**Comment by gingerwizard** [comment]
@sujuanliu 2.0 out. please test.

**Comment by bossinc** [comment]
Closing this issue. Feel free to reopen if this hasn't been resolved.
