### ISSUE TITLE
Nullable(T): column: unhandled type Bool

### ISSUE THREAD

**Issue by AntonFriberg** [grafana/clickhouse-datasource#141]
**Describe the bug**
Does not support querying Nullable(Bool) columns.

**Versions**
Grafana: v8.5.3
Plugin: v1.1.2

**Query**
A text example of the query ( if possible ).

```sql
SELECT toNullable(True)
```

**To Reproduce**
Execute query above in the explorer view towards a configured ClickHouse database.

**Expected behavior**
To be able to query Nullbable(Bool) with the same excellent behavior as other types. 

**Screenshots**
[
![Screenshot 2022-06-21 at 11-54-11 Explore - ClickHouse - Grafana](https://user-images.githubusercontent.com/14290517/174772304-09dd2e6e-4d9b-43ac-bd4e-4d3a551b7dbf.png)
](url)

**Comment by bossinc** [comment]
@gingerwizard

**Comment by gingerwizard** [comment]
This will be addressed when we update the driver to 2.0. Next release.

**Comment by gingerwizard** [comment]
@bossinc you can close this - fixed in v2.
