### ISSUE TITLE
A backend interface of the plugin

### ISSUE THREAD

**Issue by heanlan** [grafana/clickhouse-datasource#145]
**Is your feature request related to a problem? Please describe.**

The use case is: we are trying to add e2e test of some self-defined Grafana dashboards, with clickhouse-datasource plugin as the datasource plugin. We want to test the query correctness, by putting some data into the clickhouse db, and checking the query result. We need the tests to be run without a browser, so Cypress e2e test is not an option. While Grafana official HTTP API doesn't offer such an API to talk to the datasource and retrieving the query result, I'm wondering if our plugin offers such an endpoint? Or we can only directly talk to the clickhouse server endpoint? Thanks in advance.

**Comment by bossinc** [comment]
You can get retrieve query results using `api/ds/query`. The results will be in data frames though. https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#query-a-data-source

**Comment by heanlan** [comment]
Thanks. It helps!
