### ISSUE TITLE
Filters don't allow you to add in custom values

### ISSUE THREAD

**Issue by bputt-e** [grafana/clickhouse-datasource#156]
**Describe the bug**
When using the query builder, if I want to add a filter that doesn't exist in the dropdown, when pressing enter, it doesn't add the field as a filter. Adding custom fields works fine for the fields dropdown, just not for filters.

**Versions**
Grafana: 9.0.2
Plugin: 1.1.2

**To Reproduce**
1. Go to explore
2. Select clickhouse plugin
3. Select database
4. Select table
5. Select fields
6. Click Add filter button
7. Type in a custom field and hit enter

**Expected behavior**
I expect it to add the field that I want to filter by

**Additional context**
We're using the MAP datatype, so while the column shows up in the fields/filter dropdown, we have to use it like ```mycol['mykey']```

**Comment by cletter7** [comment]
Hi @bputt-e, this should be fixed in plugin version `2.0.4`. Could you check please?
