### ISSUE TITLE
No option to select time series field

### ISSUE THREAD

**Issue by Burny-McBurnFace** [grafana/clickhouse-datasource#161]
**Describe the bug**
I have a ClickHouse DateTime field that does not show as an option for selecting as the time series field in query builder.

**Versions**
Grafana 9.0.4, plugin 1.1.2

**Query**
Can't finish building

**To Reproduce**
Have a table with a DateTime field named `dt`. Try to select for the time series field.

**Expected behavior**
dt is selectable.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by bossinc** [comment]
A fix for this is in main. We will release a new version soon!

**Comment by Burny-McBurnFace** [comment]
Excellent! Is there an ETA on the new release?

**Comment by chenlujjj** [comment]
Still not work yet on latest version
