### ISSUE TITLE
adhoc filter generate wrong sql

### ISSUE THREAD

**Issue by libinyl** [grafana/clickhouse-datasource#162]
**Describe the bug**

ad hoc filter generated wrong sql ( missing quote ? )  when the column type is String and the value is a numeric string. 

**Versions**
Grafana and Plugin versions.

Grafana version: 8.2.7
plugin version: 1.1.2

**Query**
please look at the screenshot below

**Expected behavior**

always generate correct sql

**Screenshots**
![image](https://user-images.githubusercontent.com/33002863/183280647-19c24fe2-b214-4c63-81ae-9c45996e2bcd.png)

table description:

![image](https://user-images.githubusercontent.com/33002863/183280896-be1ae544-a8ea-44f6-ad8f-e07242c56879.png)

please forgive my poor english

**Comment by bossinc** [comment]
I believe changes to Grafana core will need to be made to solve this issue. Right now we try to parse the ad hoc query 
 results into a number. If the results do not parse into a number we assume it's a string.

You could work around this issue by using a template variable for `app_id` and add a `where` clause to your query using the template variable.

**Comment by libinyl** [comment]
> I believe changes to Grafana core will need to be made to solve this issue. Right now we try to parse the ad hoc query results into a number. If the results do not parse into a number we assume it's a string.
> 
> You could work around this issue by using a template variable for `app_id` and add a `where` clause to your query using the template variable.

thanks for the reply; BTW, does the Grafana team know about this issue, or  have a plan to fix it? thanks again.

**Comment by bossinc** [comment]
I've made the team aware of this issue. I am not sure how/when this will be fixed. I'll update this ticket when I learn more 🙂

**Comment by libinyl** [comment]
> I've made the team aware of this issue. I am not sure how/when this will be fixed. I'll update this issue when I learn more 🙂 

thanks！！

**Comment by bossinc** [comment]
This should no longer be as of the 2.0 release. Please reopen if this is not fixed.
