### ISSUE TITLE
Support for functions

### ISSUE THREAD

**Issue by kirederik** [grafana/clickhouse-datasource#18]
## Why are we doing this work?
To make it simpler to use the plugin

## Acceptance
* Commonly used functions are available
* Docs are updated with the supported functions

**Comment by kirederik** [comment]
What functions should we really support? Who can we ask about it?

**Comment by kirederik** [comment]
We chatted during planning and we were a bit unsure on what are the functions we really want to support. The legacy plugin ships the following functions:

* `$rate(cols...)`: converts query results as "change rate per interval"
* `$columns(key, value)`: query values as array of [key, value], where key will be used as label
* `$rateColumns(key, value)`: a combination of `$columns` and `$rate`
* `$perSecond(cols...)`: converts query results as "change rate per interval" for Counter-like(growing only) metrics
* `$perSecondColumns(key, value)`: a combination of `$columns` and `$perSecond` for Counter-like metrics

It's unclear wether those are common use cases on Clickhouse or just a choice made by the developer of the plugin. 
 
@josiahg, do you have insights on this one?

**Comment by oplehto** [comment]
Long-time ClickHouse-Grafana user here. The functions are pretty essential in use cases that go beyond just visualizing a single column. 

For me, the `$perSecondColumns` and `$columns` are the commonly used ones. Also the `$conditionalPredicate` is very useful.

**Comment by gingerwizard** [comment]
@kirederik i'm not sure we need these. Philosophically i think we agreed to move away from creating a sub language and simplifying this through either a query builder and/or query templates and/or improvements in ClickHouse.

**Comment by kirederik** [comment]
@gingerwizard good point

I'll close this one and we can keep an eye for community requests beyond the macros we currently support
