### ISSUE TITLE
Support summary histogram in explore view + drill down

### ISSUE THREAD

**Issue by gingerwizard** [grafana/clickhouse-datasource#182]
Currently, explore only renders the histogram based on the returned results. Other plugins (Loki, Elasticsearch) generate a histogram for the entire time range based on an aggregation/GROUP BY.
We should add this capability.

**Comment by mshustov** [comment]
We want to build histogram data on a backend. So far, I found a place where the response data frames are built is `sqld` abstraction `getFrames` function.
Is there any other way that we could return an additional frame with a histogram directly from data source plugin? Given CH datasource only initialises a `sql.DB` conn I don't see such possibility. Maybe you and your team have some ideas?
Otherwise, it means we will have to extend `sqld` API.

**Comment by jkaflik** [comment]
Is there documentation/example of how the structure data frame, so the histogram is displayed?

**Comment by asimpson** [comment]
Making sure this doesn't get dropped. I need to run down some more info on how to structure the data frame. I'll ping back here when I have  more information.

**Comment by jkaflik** [comment]
@asimpson, we went further with investigation and found it's not really about data frame structure, but data source has to implement `DataSourceWithSupplementaryQueriesSupport` on UI side. This is our finding based on Loki and Elasticsearch data source plugins.

@mshustov FYI, since you last been looking on this.

**Comment by mshustov** [comment]
> Then UI does an additional query that should be mutated with some aggregation function and group by. This is our finding based on Loki and Elasticsearch data source plugins.

@asimpson Could you confirm whether @jkaflik conclusions are correct? Is there guidance on query mutations? Is there any tooling helping to adjust the query?

**Comment by mshustov** [comment]
> Then UI does an additional query that should be mutated with some aggregation function and group by. This is our finding based on Loki and Elasticsearch data source plugins.

I took a look at the Elasticsearch implementation. I think we can start without access to `queryLogsVolume` function, as long as we can make a correct aggregation request within `getSupplementaryQuery` and return `Observable<DataQueryResponse>`.  Even though, it requires the implementation of some manual [pre-](https://github.com/grafana/grafana/blob/98596c36ad733d159c0539eae160d0677f97ae7a/public/app/core/logsModel.ts#L686-L694) and  [post-processing](https://github.com/grafana/grafana/blob/98596c36ad733d159c0539eae160d0677f97ae7a/public/app/core/logsModel.ts#L726-L736)

The default behavior of Elasticsearch datasource is:
- to create a request with [date histogram aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html) with bucketing on interval size based on the time range  (see the logic [here](https://github.com/grafana/grafana/blob/98596c36ad733d159c0539eae160d0677f97ae7a/public/app/core/logsModel.ts#L819)) 
- if `logLevelField` field is present (configured in the datasource settings): to count the number of logs of provided log level in each bucket.

We can try to transform a query to attach [histogram](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/parametric-functions/#histogram) aggregation calculated on ClickHouse server. Some usage examples: https://clickhouse.com/blog/working-with-time-series-data-and-functions-ClickHouse 

If we can make it work, we can consider extracting more helpers from https://github.com/grafana/grafana/blob/98596c36ad733d159c0539eae160d0677f97ae7a/public/app/core/logsModel.ts 
WDYT @asimpson ?

**Comment by asimpson** [comment]
> Could you confirm whether @jkaflik conclusions are correct? Is there guidance on query mutations? Is there any tooling helping to manipulate a query?

We don't have any standard tooling or docs for implementing histograms, it is something we've discussed but haven't had the time to implement it yet. Unfortunately that means looking at Elastisearch and other datasource plugins is our best bet for guidance. 

> We can try to transform a query to attach [histogram](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/parametric-functions/#histogram) aggregation calculated on ClickHouse server

I think this makes total sense! It would also hopefully reduce the amount of work the datasource would need to do to support Histograms.
