### ISSUE TITLE
Visual query builder

### ISSUE THREAD

**Issue by kirederik** [grafana/clickhouse-datasource#19]
## Why are we doing this work

We'd like to provide a good query building experience for the users of the Clickhouse datasource. On https://github.com/grafana/google-bigquery-datasource/issues/11, we built a new and improved visual query builder that we'd like to adopt across all our datasources.

## Acceptance
* Datasource is updated to use the new visual query builder

**Comment by scottlepp** [comment]
Fixed by #48
