### ISSUE TITLE
Regex error in Safari: "Invalid regular expression: invalid group specifier name"

### ISSUE THREAD

**Issue by coelho** [grafana/clickhouse-datasource#192]
**Describe the bug**
Trying to use the plugin in Safari results in the error:
`Invalid regular expression: invalid group specifier name Instantiating https://.../public/plugins/grafana-clickhouse-datasource/module.js Loading plugins/grafana-clickhouse-datasource/module`

**Versions**
Grafana 9.1.2
Safari 15.6
Datasource 2.0.0

**To Reproduce**
1. Open in Safari

**Expected behavior**
There should be no error.

**Screenshots**
![Image](https://coelho.ninja/sHISVFHIgSFGUJySTb+9CIbgfIc=)

**Additional context**
According to a quick Google, likely related to Safari not supporting Regex look-behind?
https://caniuse.com/js-regexp-lookbehind

**Comment by dgloeckner** [comment]
Same here. This is a pretty sever regression. 

![image](https://user-images.githubusercontent.com/6209281/189113845-d0d952e9-79a2-467b-bd95-de079d232348.png)

**Comment by coelho** [comment]
Hi @bossinc If it's not too much trouble, can a new version be pushed to https://grafana.com/grafana/plugins/grafana-clickhouse-datasource/ with the fixed version?
Thank you!

**Comment by bossinc** [comment]
@coelho 2.0.1 is live 😃

**Comment by gingerwizard** [comment]
Thanks @bossinc 👏
