### ISSUE TITLE
Reproduce CI steps in GitHub Actions

### ISSUE THREAD

**Issue by mshustov** [grafana/clickhouse-datasource#194]
**Is your feature request related to a problem? Please describe.**
When a developer opens a PR against the repository, a few CI checks are run: 
- frontend tests (Github Actions)
- backend tests (Github Actions)
- a check (Drone)

If a Drone check fails, non-Grafana employees do not have access to logs, which introduces a long delay in getting feedback.

**Describe the solution you'd like**
Reproduce (or move) Drone checks in GitHub Actions so that anyone from the OSS community can access the results.

**Comment by SpencerTorres** [comment]
Is this still relevant after https://github.com/grafana/clickhouse-datasource/pull/754 and https://github.com/grafana/clickhouse-datasource/pull/737 ?

cc @asimpson

**Comment by asimpson** [comment]
Yep, good call out!
