### ISSUE TITLE
Unexpected query error

### ISSUE THREAD

**Issue by mxlxm** [grafana/clickhouse-datasource#195]
**Describe the bug**

query with `WITH Clause` contains `$__timeFilter(time)` must have a black space before right parenthesis.
**Versions**
Grafana and Plugin versions.

**Query**
this query can work
```
with (select max(time) from unicost.bill where $__timeFilter(time) ) as mtime
SELECT cloud, sum(realPrice) cost FROM unicost.bill WHERE time=mtime  GROUP BY cloud ORDER BY cost DESC;
```
while this one can not
```
with (select max(time) from unicost.bill where $__timeFilter(time)) as mtime
SELECT cloud, sum(realPrice) cost FROM unicost.bill WHERE time=mtime  GROUP BY cloud ORDER BY cost DESC;
```
**To Reproduce**

**Expected behavior**
they are the same query.

**Screenshots**

**Additional context**

**Comment by bossinc** [comment]
I was able to reproduce the bug. Thank you for also finding a workaround!

**Comment by sasklacz** [comment]
This also fails when other macros are used. Investigating

**Comment by sasklacz** [comment]
Also this is a problem in our sqlds plugin. Was able to find at least one more failing case:

```
(select min(time) from table where $__timeFilter(time) ) OK
(select min(time) from table where $__timeFilter(time)) NOK
select * from foo where $__timeFilter(cast(sth as timestamp)) OK
select * from foo where $__timeFilter(cast(sth as timestamp) ) NOK
```

**Comment by sasklacz** [comment]
2.0.2 released
