### ISSUE TITLE
Calculated field Alias is not available for subsequent calculated fields in transforms

### ISSUE THREAD

**Issue by e-mars** [grafana/clickhouse-datasource#197]
**Describe the bug**
After adding a calculated field in Transforms and setting a field alias, the new alias does not appear in the drop down list subsequent transforms

**Versions**
Grafana: 9.1.3
ClickHouse Plugin version : 2.0.0

**Query and to reproduce**
![Test_query_sources](https://user-images.githubusercontent.com/18219420/189392328-d9c6dbde-7066-48de-b96f-e69cf0e9a72d.png)

![Test_missing_field_in_dropdown](https://user-images.githubusercontent.com/18219420/189392634-b4b2ce77-f34b-458c-85c5-93e99e510549.png)

**Expected behavior**
new alias field should show.

**Comment by bossinc** [comment]
As far as I know, you can't use calculated fields in other calculated fields. Transforms are not handled by the plugin. They are handled on the Grafana side. You might get a more detailed response if you create an issue in the Grafana repo. 😃
