### ISSUE TITLE
Adhoc filters not working for distributed tables

### ISSUE THREAD

**Issue by jmassiot** [grafana/clickhouse-datasource#198]
**Describe the bug**

Adhoc filters are not working for distributed clickhouse tables.
Since the version `2.0.0` of the plugin, adhoc filters are implemented through the `additional_table_filters` settings (introduced in  clickhouse 22.7).
And the situation is as follow:
* let's imagine a clickhouse database with 2 tables `t1_distributed` & `t1_local`
  * `t1_distributed` being a distributed table on top of `t1_local`
  * `t1_local` containing 2 fields `f1` & `f2`
* we then define a dashboard with adhoc filters on the `f2` field
* we add a "log panel" that is doing a `SELECT f1 from t1_distributed`
* then
  * if an adhoc filter is specified for the field `t1_distributed.f2`
    * the following query will be built by the plugin `SELECT f1 from t1_distributed settings additional_table_filters = {'t1_distributed': 'f2 = xxx'}`
    * this query will actually not do its job of filtering
    * i guess it is coming from the fact that `additional_table_filters` are applied by clickhouse when it reads the table....but distributed tables are not read.....
    * if i replace in the built query, within the `additional_table_filters` settings, `t1_distributed` with `t1_local` (so a query like `SELECT f1 from t1_distributed settings additional_table_filters = {'t1_local': 'f2 = xxx'}), then it is working as expected
  * i gave a try to add an adhoc filter on the "local" table (while my "main" query is still on the distributed table) (ie define an adhoc filter on the fied `t1_local.f2`)
    *  then the built query by the plugin does not include any `additional_table_filters` settings (i guess there is a check in order to add additional_table_filters only on the table used in the query)

So, i cannot find any workaround here to have my adhoc filters working as expected on distributed tables.

Note than in the previous version of the plugin (where adhoc filters were managed by modiyfing the where clause of the query), it was working as expected.

**Versions**
Plugin: `2.0.0`
Grafana version:  `v9.1.1`

**Query**

**To Reproduce**
cf above

**Expected behavior**
We should have a "way" to have adhoc filters working on distributed tables.
Would one of those options be acceptable ?
* being able to use adhoc filters field from a table (the local table) that is not the one of the "main" query (where a distributed table is used)
* being able to define a mapping between distributed table & local tables in a "constant" variable ?
* being able to retrieve the mapping between "distributed" & "local" tables directly through clickhouse (through queries to `system.tables` clickhouse table)

**Screenshots**

**Additional context**

**Comment by jmassiot** [comment]
Thank you for the update.
From the clickhouse 2022 changelog documentation `Introduced settings additional_table_filters. Using this setting, you can specify additional filtering condition for a table which will be applied directly after reading`, this `applied directly after reading` should be the root cause of this "issue" as we are not reading from the distributed table.

I don't know if distributed tables should be supported within this settings.
Actually, i am not sure to fully understand which use case this settings is supposed to tackle (vs just adding the filters within a where clause).

I was also wondering how those `additional_table_filters` are behaving with regards to performance vs putting the filters within a where clause (especially when you filter on a field that is part of your "primary/order by"  indices or part of skip indices like bloom filter skip indices).
I've just done a test on one of my table where i have a "bloom filter" skip index defined and i can confirm that the performance are much worst when using `additional_table_filters` vs using a where clause.
I go from `0.5 seconds` to `6 seconds` ! 

I have the feeling that for the `adhoc filters` use case, the approach used in the previous version (ie adding them in the where clause) is a better fit.
At least, it was working extremely well on our side for all our use cases and we were very happy with it :-).

Do you think that the choice of going with a `where clause` approach can be reconsidered ?

**Comment by jmassiot** [comment]
@gingerwizard thank you for the update.
I understand your point about the query parsing and your will to delegate this work to clickhouse.
I’ll follow up on the clickhouse ticket.

On my side, I am still not clear about this additional_table_filters settings (why was it introduced by the clickhouse team? and for which use cases?).
And actually there may 2 topics not necessarily related on this topic:
- to have it working on distributed tables
- to have it as efficient as a where clause when you filter on indices (either the primary ones or skip indices ones)

**Comment by gingerwizard** [comment]
It was introduced to avoid parsing of the ClickHouse dialect on the client side - the dialect is not ANSII SQL and injecting clauses into WHERE becomes more complex once you consider JOINS and subqueries. We had numerous issues and maintaining a full AST parser for SQL is non-trivial - especially when it's not ANSII SQL. We thus push the work down to the place this can be done best - in ClickHouse.  The use case is mainly UIs that need to add filters - so any BI or eqv. tool.

Agreed above two need to work.

**Comment by gingerwizard** [comment]
This has been fixed in ClickHouse itself - https://github.com/ClickHouse/ClickHouse/pull/42322

This fix will be backported to 22.7/22.8/22.9 and will also be in 22.10.
We've also confirmed that secondary indexes should now work.
@jmassiot reopen if you encounter issues on the next CH version or a backported release.
 
@bossinc close please.
