### ISSUE TITLE
Support for multiple authentication methods

### ISSUE THREAD

**Issue by kirederik** [grafana/clickhouse-datasource#20]
## Why?

There are different ways to connect to clickhouse. We should support as many as we can#18 

## Acceptance
* It's possible to configure the datasource with:
  - [x] TCP
  - [x] TLS
    - [x] With a custom CA cert
    - [x] With TLS Skip
    - [x] With MTLS
  - [ ] ...?

**Comment by kirederik** [comment]
@scottlepp looking at the code, this seems mostly done? Is there any other way to connect to clickhouse that we're not currently supporting?

**Comment by scottlepp** [comment]
@kirederik its possible to connect over http vs the native tcp protocol.  However that seems just an alternative that we don't need to support (unless the clickhouse-go driver has some unforeseen limitations).

Fixed by #21
