### ISSUE TITLE
Incorrect behavior using "all" variable value

### ISSUE THREAD

**Issue by Catwoolfii** [grafana/clickhouse-datasource#201]
**Describe the bug**
After updating the plugin to version 2.0 in the variable settings, the "All" option began to work incorrectly: now if you select "all", then all variable values are added to the query. In previous versions (before 2.0), there was a different behavior: when selecting "all" in the variable, operators with such a variable were not included in the query.

**Versions**
Grafana 8.5.10, plugin 2.0.1

**Query**
```
SELECT fromhost AS host, count(priority) AS priority
  FROM logs.syslog
 WHERE $__timeFilter(devicereportedtime)
       AND message LIKE '%$find_in_messages%'
       AND message LIKE '%$search_in_found%'
       AND fromhost IN ($host)
       AND priority IN ($priority)
       AND facility IN ($facility)
       AND syslogtag IN ($syslogtag)
 GROUP BY fromhost
 ORDER BY count(priority) DESC LIMIT 10
```

**To Reproduce**
1. Add variables of "query" type, enable "all" option in settings
2. Select "all" in the list of variable values
3. Add variables to sql query conditions
4. Check execution of query in the "query inspector"

**Expected behavior**
Waiting for the behavior of the plugin before version 2.0 using the "all" option in the variable (see description)

**Screenshots**
![grafana_clickh1](https://user-images.githubusercontent.com/13075570/190399080-d0846c80-680c-497a-809a-08abe7e9c349.PNG)
![grafana_clickh2](https://user-images.githubusercontent.com/13075570/190399083-3100377c-0550-4bec-9fda-90990d58d7fc.PNG)

**Additional context**
-

**Comment by bossinc** [comment]
@Catwoolfii The plugin no longer supports automatically removing template variables if `all` is selected. Please use `$__conditionalAll(condition, $templateVar)` to do the same thing. You can read more about the `conditionalAll` macro here: [Macros](https://grafana.com/grafana/plugins/grafana-clickhouse-datasource/#Macros)
