### ISSUE TITLE
Provide error details in SQL editor

### ISSUE THREAD

**Issue by mshustov** [grafana/clickhouse-datasource#206]
**Describe the bug**
No error details are provided when sending a non-valid query.

**Versions**
Grafana v9.1.6
plugin 2.0.1

**Query**
 for example, `SELECTffff`

**To Reproduce**
1. Go to Explore
2. Switch to SQL editor
3. Send `SELECTffff` query
4. See `Query error: 500 Internal Server Error`

**Expected behavior**
I'd expect an error message about invalid syntax, `unknown identifier`, `unknown table` to be provided. Debugging a typo in a query without a meaningful error message is not the best UX.

**Screenshots**
![2022-09-30_18-41-00](https://user-images.githubusercontent.com/3198181/193317470-93be997a-8aaa-416d-9b10-3496ff87f81b.png)

**Comment by gingerwizard** [comment]
![image](https://user-images.githubusercontent.com/12695796/196518961-19efa882-9202-493b-91a9-0aee75380b20.png)

this is quite descriptive.

**Comment by gingerwizard** [comment]
Same error on explore as the one above.

**Comment by gingerwizard** [comment]
Versions
Grafana v9.0.1
plugin 2.0.1

Maybe we've dropped this info in 9.1.x. Or are you connecting over HTTP?

**Comment by gingerwizard** [comment]
HTTP isn't great but still better than 500

![image](https://user-images.githubusercontent.com/12695796/196520096-9aaef913-d8b3-4257-a6f6-0c3a68547c06.png)

**Comment by gingerwizard** [comment]
Hmm using 9.2.1 grafana it seems like this has regressed.
