### ISSUE TITLE
HTTP Connection not working for CH Server below 21.4

### ISSUE THREAD

**Issue by derN3rd** [grafana/clickhouse-datasource#215]
**Describe the bug**
Just wanted to make aware that there is a bug in the clickhouse-go lib that breaks the HTTP connection method if the CH server is below version 21.4.
Once https://github.com/ClickHouse/clickhouse-go/issues/780 is fixed, the clickhouse-datasource plugin needs a new release to also fix this, afaik.

Thanks in advance

**Versions**
Plugin 2.0.1

**Query**
All queries afaik

**To Reproduce**
1. have a server on CH version 20.1 i.e.
2. setup grafana and the clickhouse-datasource plugin with HTTP connections
3. Try to run a query with some time data
4. All queries fail with `Code: 46, e.displayText() = DB::Exception: Unknown function timeZone. Maybe you meant: ['timezone','toTimeZone']: While processing timeZone()`

**Expected behavior**
All queries work as expected

**Comment by gingerwizard** [comment]
Not a supported version but will be fixed when the client is updated to 2.4.0. https://github.com/ClickHouse/clickhouse-go/pull/781
