### ISSUE TITLE
Display full text for metric errors

### ISSUE THREAD

**Issue by e-mars** [grafana/clickhouse-datasource#217]
**Is your feature request related to a problem? Please describe.**
If there is an error in fetching data, the plugin only displays a generic error as in screenshotsbut not the full error received to help troubleshoot the issue.

**Describe the solution you'd like**
Display full error from ClickHouse

**Describe alternatives you've considered**
View logs or try to reproduce using CLI or curl for particular failing query.

**Comment by rlazimi-dev** [comment]
Thank you @e-mars!

This issue also occurs for ClickHouse version:
```
22.2.2.1
```

and Grafana Version:
```
Version 8.3.2 (commit: afb9e8e5f3, branch: HEAD)
```

**Comment by e-mars** [comment]
on roadmap: https://github.com/grafana/clickhouse-datasource/issues/206

**Comment by gingerwizard** [comment]
@rlazimi-dev do you have any examples here? timeouts show as a context exceeded which defn needs to be improved. Other errors e.g. `SELECT x` are quite descriptive, however. Any other cases? @e-mars

**Comment by gingerwizard** [comment]
timeouts here https://github.com/grafana/clickhouse-datasource/issues/187

**Comment by gingerwizard** [comment]
Issue https://github.com/grafana/clickhouse-datasource/issues/206 not reproducible.

**Comment by e-mars** [comment]
@gingerwizard 
example below:
<img width="1920" alt="error" src="https://user-images.githubusercontent.com/18219420/196676984-00ae19bd-3a76-4beb-b0a7-bc9c4847ba7a.png">
