### ISSUE TITLE
Compare to vertamedia clickhouse plugin?

### ISSUE THREAD

**Issue by abh** [grafana/clickhouse-datasource#22]
It'd be helpful if the documentation acknowledged the existing community / vertamedia clickhouse plugin and had a few notes on what the differences are.

**Comment by scottlepp** [comment]
This is the official plugin supported/maintained by Grafana.

* The Vertamedia plugin uses AngularJS which has reached EOL.  This could introduce security issues.
* This plugin will include a more robust visual query builder, a core React component of Grafana.
* This plugin leverages the SQL lib from core Grafana SDK.
* The goal is to rely more on core Grafana components and reduce custom code/maintenance here.

Over time the features here will continue to grow.  We don't want to keep updating the docs as to what new features exist here vs Vertamedia.
