### ISSUE TITLE
Could it support use log mode at the explore UI?

### ISSUE THREAD

**Issue by hanjm** [grafana/clickhouse-datasource#23]
like elasticsearch plugin dodes.
![image](https://user-images.githubusercontent.com/7621241/147406274-f409d172-254d-4d18-95a4-72bff335eb7d.png)

**Comment by scottlepp** [comment]
@hanjm if you use the log_time alias for the time field it will use the logs panel see:  https://github.com/grafana/clickhouse-datasource#visualizing-logs-with-the-logs-panel

**Comment by bputt-e** [comment]
@scottlepp I'm thinking @hanjm wants the datasource to appear in the dropdown at the top of the explore section in grafana like the example below...The link you sent appears to be related to queries ran on a dashboard?

![image](https://user-images.githubusercontent.com/60984725/156656060-8efb2b2e-995a-49db-826c-9f7a9d8e2213.png)

**Comment by hanjm** [comment]
@scottlepp  cool feature! Thank you 🚀

**Comment by hanjm** [comment]
hi, @scottlepp Could you help make a release?  :)
