### ISSUE TITLE
Plugin health check failed

### ISSUE THREAD

**Issue by Jessica-Y-J** [grafana/clickhouse-datasource#231]
The plugin fails when I click the 'Save & Test' button, I am sure the info of db  is correct,  but  I don't know what is failing. Any idea or suggestions, please! :) :)

plugin version: 2.0.2 , Operating System:  centos7.2

Some logs : 

logger=datasources t=2022-10-27T15:18:21.285974046+08:00 level=debug msg="Querying for data source via SQL store" id=22 orgId=2
logger=secrets.kvstore t=2022-10-27T15:18:21.288552609+08:00 level=debug msg="got secret value from cache" orgId=2 type=datasource namespace=ClickHouse
logger=plugin.grafana-clickhouse-datasource t=2022-10-27T15:18:21.298273435+08:00 level=error msg="clickhouse [execute]:: 404 code: _\ufffd hČ\ufffd\ufffd\u0010&\ufffd\ufffdO\ufffd\ufffd\\\ufffd\ufffd\u0000\u0000\u0000\ufffd\u0000\u0000\u0000\ufffd(Code: 46, e.displayText() = DB::Exception: Unknown func\u0012\u0000\ufffd\u000f timeZone. Maybe you meant: ['\u001d\u0000\ufffdzone','toT\r\u0000\ufffd\u0005] (version 219.1.1)\n"
logger=plugin.grafana-clickhouse-datasource t=2022-10-27T15:18:21.304568315+08:00 level=debug msg="2022/10/27 15:18:21 ERROR: [core] [Server #1] grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=2 uname=admin t=2022-10-27T15:18:21.304772824+08:00 level=error msg="Plugin health check failed" error="failed to check plugin health: health check failed" remote_addr=127.0.0.1 traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=2 uname=admin t=2022-10-27T15:18:21.304875278+08:00 level=error msg="Request Completed" method=GET path=/api/datasources/22/health status=500 remote_addr=127.0.0.1 time_ms=25 duration=25.020928ms size=85 referer=http://http://localhost:3000//grafana/datasources/edit/gRCtHkV4k traceID=00000000000000000000000000000000 handler=/api/datasources/:id/health

**Comment by gingerwizard** [comment]
This looks like a result of the version of ClickHouse you're using.  see https://github.com/ClickHouse/clickhouse-go/pull/781. Are you on a CH version <= 21.4 by any chance? @Jessica-Y-J

**Comment by gingerwizard** [comment]
See https://github.com/grafana/clickhouse-datasource/issues/215
