### ISSUE TITLE
DESC TABLE expression not work when table name contains dot

### ISSUE THREAD

**Issue by chenlujjj** [grafana/clickhouse-datasource#232]
**Describe the bug**
When table name contains dot symbol, the DESC TABLE expression does not work

**Versions**
Grafana and Plugin versions.
grafana: 9.1.7
plugin: 2.0.2

**Query**
DESC TABLE db.a.b

table name is a.b

**Comment by chenlujjj** [comment]
I have fixed this locally

**Comment by gingerwizard** [comment]
try in backticks around the table name? e.g. 
```
DESC TABLE `db.a.b`
```

If not, can you raise a PR or suggest changes? @chenlujjj

**Comment by chenlujjj** [comment]
My solution is:
```
DESC TABLE db.`a.b`
```
See this commit: https://github.com/chenlujjj/clickhouse-datasource/commit/c82391af7526b6adb039e7b5b267340790e6f7f8

But it contains some inrelevant changes. Maybe I can checkout another branch and make a clean PR.
