### ISSUE TITLE
Resizable code editor

### ISSUE THREAD

**Issue by seanlaff** [grafana/clickhouse-datasource#235]
The 8 lines isn't enough to write a sufficiently complicated query.

The mysql plugin has a pop-out for its monaco editor

**Comment by gingerwizard** [comment]
@bossinc @mikhail

**Comment by mikhail** [comment]
Why Grafana?

**Comment by seanlaff** [comment]
[v9.2.0 (c7eea48209)](https://grafana.com/docs/grafana/latest/release-notes/release-notes-9-2-0/)

**Comment by cletter7** [comment]
Hey @seanlaff, it's possible to switch the code editor to "auto-expand" mode by clicking the "plus" icon in the top left corner of the code editor.

![image](https://user-images.githubusercontent.com/1436174/203538569-6dd5ad95-f0ef-4fd2-9756-d71274dadad3.png)

You can find more info here: https://github.com/grafana/clickhouse-datasource/pull/64.

Does it solve your use case?

**Comment by seanlaff** [comment]
Ah- thank you that did the trick! I'd say the ux is not that discoverable, maybe the grafana team can unify this in their underlying CodeEditor component.

**Comment by cletter7** [comment]
> Maybe the grafana team can unify this in their underlying CodeEditor component.

I agree it's not obvious. We'll think about how this can be unified.
