### ISSUE TITLE
Breaking change on `$__interval_s` on v2.0.4 (working on v1.1.2)

### ISSUE THREAD

**Issue by bfreis** [grafana/clickhouse-datasource#249]
**Describe the bug**

There's a breaking change on `$__interval_s` on v2.0.4 (vs v1.1.2). All my dashboards that use it broke completely :-( .

The translated query ends up with a lot of text removed. See example query and screenshot below.

I found a workaround by adding parenthesis after the macro: `$__interval_s()`.

Can you please make sure to _document_ breaking changes on the Release Notes? Also, can you please make sure to _not break_ the syntax `$__interval_s()` in future updates, so I don't have to update all my dashboards another time? Adding a unit test to ensure that `$__interval_s()` works would be greatly appreciated, to ensure that there won't be another regression on this.

Thank you!

**Versions**
Grafana and Plugin versions.

Grafana: Enterprise v9.3.0-beta1 (78f0340031)
Plugin: v2.0.4

**Query**

```
SELECT toStartOfInterval(event_time, INTERVAL $__interval_s SECOND) AS time
,metric
,avg(value)
FROM system.asynchronous_metric_log
WHERE $__timeFilter(event_time)
  AND (metric like 'LoadAverage%')
GROUP BY time, metric
ORDER BY time
```

The translated query is:

```
SELECT toStartOfInterval(event_time, INTERVAL 2
FROM system.asynchronous_metric_log
WHERE event_time >= '1669866809' AND event_time <= '1669870409'
  AND (metric like 'LoadAverage%')
GROUP BY time, metric
ORDER BY time
```

Note how everything until the `FROM` clause is removed.

I noticed that if there's _any_ other `()` on the SELECT clause (e.g., `SELECT ..., hostname()`), then everything until that `()` gets replaced — this is what led me to find the workaround I described above.

**To Reproduce**
1. Go to "Explore", select a ClickHouse datasource.
2. Click on "SQL Editor".
3. Type the query above.
4. Open the "Inspector"
5. Click the "Query" tab
6. Clich the "Refresh" button within that tab
7. Note the broken translated query, as well as the error returned from ClickHouse.

**Expected behavior**

The query above should return data.

**Screenshots**

<img width="1867" alt="image" src="https://user-images.githubusercontent.com/261623/204969395-1535caf5-f5aa-40ab-bfcc-04ec4edcdf6e.png">

**Additional context**

**Comment by alexandrpaliy** [comment]
Same problem here, plugin version 2.0.4, grafana 9.3.0 (self-hosted).

Query
```
SELECT
    (intDiv(toUInt32(time), $__interval_s ) * $__interval_s ) * 1000 AS t,
    countIf(t1.column1 = 'val1') AS c,
    multiIf(t2.column2 = '', '<empty>', service) AS service
FROM db1.table1 AS t1
...
```
becomes
```
SELECT
    (intDiv(toUInt32(time), 900 AS c,
    multiIf(t2.column2 = '', '<empty>', service) AS service
FROM db1.table1 AS t1
...
```

Looks like `$__interval_s` macro expects as pair of parentheses (and, thus, removes everything until (and including) the first ')' it finds), because this
```
SELECT
    (intDiv(toUInt32(time), $__interval_s() ) * $__interval_s() ) * 1000 AS t,
    countIf(t1.column1 = 'val1') AS c,
    multiIf(t2.column2 = '', '<empty>', service) AS service
FROM db1.table1 AS t1
...
```
works ok
```
SELECT
    (intDiv(toUInt32(time), 900 ) * 900 ) * 1000 AS t,
    countIf(t1.column1 = 'val1') AS c,
    multiIf(t2.column2 = '', '<empty>', service) AS service
FROM db1.table1 AS t1
...
```
