### ISSUE TITLE
Change database before query

### ISSUE THREAD

**Issue by abh** [grafana/clickhouse-datasource#256]
I'm using a dictionary in a query (with the query builder) as `dictGet("some_dictionary", "field", id)`. This looks for the dictionary in the default database.

I tried using "$database.some_dictionary", but that macro doesn't exist.

It'd be helpful if the clickhouse datasource used the specified database before running the query, so an unqualified table or dictionary name use the database specified in the panel.

**Comment by cletter7** [comment]
Hi @abh. Could you share which fields do you fill in, and how the result query looks like?

**Comment by bossinc** [comment]
Hello, @abh the query builder doesn't play nice with CH macros, but there has been an update to the query builder that might work with macros. If you give it a try with the query builder again and it doesn't work, I would suggest using the query text view 🙂
