### ISSUE TITLE
Group By query in chart view

### ISSUE THREAD

**Issue by heanlan** [grafana/clickhouse-datasource#26]
Does it support group by query result in any chart view? I tried with time series, pie chart, both didn't work. I'm not sure what's the correct way to make it work. Any help would be much appreciated. 

An example:
I do see the results are available in table view.
<img width="1017" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/80798942/148458732-31afdb16-35d8-4418-beb8-1e93f8adfe2e.png">

When I switch back to pie chart, it supposed to give me multiple slices with different pod names and records counts, but resulted in only showing the count of one single pod. 
<img width="1020" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/80798942/148458724-f96484b9-8d3c-43ff-b957-20529ce1b13c.png">

The same query did work with vertamedia clickhouse plugin.
<img width="1022" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/80798942/148616142-c1c379c4-d961-4af4-aeed-eb7c567bf071.png">

**Comment by scottlepp** [comment]
@heanlan works fine for me.  Under "value options" do you have Show > "All Values" selected?

![image](https://user-images.githubusercontent.com/6108819/150017693-e6ae96a5-09b4-490b-bca2-bff95206f8a2.png)

![image](https://user-images.githubusercontent.com/6108819/150017792-ec9d59b6-c7ab-4166-8a09-03c4f281af09.png)

**Comment by scottlepp** [comment]
@heanlan and for time series follow this convention:  https://github.com/grafana/clickhouse-datasource#multi-line-time-series

**Comment by heanlan** [comment]
Is there any way we can remove the metric value name from the legend? e.g. "bytes" in the screenshot below. 

What I want:
sourcePodName, destinationPodName
What is provided:
bytes sourcePodName, destinationPodName

![image](https://user-images.githubusercontent.com/80798942/150877735-44e126d2-edda-408b-8c7c-589a6df751e1.png)
