### ISSUE TITLE
Allow __text/__value Templating for Query Variables

### ISSUE THREAD

**Issue by fionera** [grafana/clickhouse-datasource#264]
**Is your feature request related to a problem? Please describe.**
Nearly all Database Provider allow to template the Query Variables

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by fionera** [comment]
Apparently this also works but it works based on the order in the select. 

`SELECT value, displayValue` works for me

**Comment by bossinc** [comment]
Hi @fionera it looks like you found the solution 😄 I am closing this issue. Feel free to reopen if I am missing something.
