### ISSUE TITLE
Cancel query on grafana dosen't kill query in clickhouse

### ISSUE THREAD

**Issue by hackaholic** [grafana/clickhouse-datasource#276]
**Describe the bug**
Cancel query on grafana doesn't kill query in clickhouse.

**Versions**
Grafana: 7.5.4
Plugin versions: vertamedia-clickhouse-datasource-2.2.3

**To Reproduce**
1. Log in to grafana load a dashboard fire a bulky query 
2. click on the cancel query
3. Now go into the clickhhouse and run **show processlist format Vertical** you will see query will be running

**Expected behavior**
When Query is canceled from the grafana gui, it should also get killed in the clickhouse

**Screenshots**
![image](https://user-images.githubusercontent.com/3721438/212823163-1babfbca-42c3-4756-8e83-e61225838239.png)

**show processlist format Vertical** output shows query running and is_cancelled = 0
![image](https://user-images.githubusercontent.com/3721438/212824172-77627cb7-384e-4686-905d-d3bec45eec5d.png)

**Comment by jkaflik** [comment]
Hi @hackaholic, what is a protocol you use? HTTP or native?

**Comment by hackaholic** [comment]
http over 8123 port.

**Comment by jkaflik** [comment]
@hackaholic, thanks for your response. Just to double check: you are using the official grafana clickhouse datasource?
Your original post mentions:
> Plugin versions: vertamedia-clickhouse-datasource-2.2.3

which is Grafana plugin maintained by Altinity
https://github.com/Altinity/clickhouse-grafana

**Comment by hackaholic** [comment]
Yes I am using plugin plugin vertamedia-clickhouse-datasource-2.2.3.

**Comment by Slach** [comment]
try to upgrade to latest 2..5.3 
if query didn't cancel, plase make issue 
https://github.com/Altinity/clickhouse-grafana/issues

**Comment by jkaflik** [comment]
In the case of the official click house data source plugin, query cancellation works as expected.
Works out of the box for native protocol. In case of HTTP, [cancel_http_readonly_queries_on_client_close](https://clickhouse.com/docs/en/operations/settings/settings/#cancel-http-readonly-queries-on-client-close) setting enabled is needed.

**Comment by asimpson** [comment]
@jkaflik I'm going to close this since it seems like there isn't any additional work here. Feel free to re-open if I'm wrong.
