### ISSUE TITLE
Can't query `SimpleAggregateFunction(groupArrayArray, Array(String))` column

### ISSUE THREAD

**Issue by hkrutzer** [grafana/clickhouse-datasource#277]
**Describe the bug**
When attempting to query an AggregatedMergeTree with a column of type `SimpleAggregateFunction(groupArrayArray, Array(String))`
I get: `sql: Scan error on column index 0, name "event_type": unsupported Scan, storing driver.Value type []string into type *string: Could not process SQL results`

**Versions**
Grafana: v9.3.2 (21c1d14e91)
Plugin: 2.0.6

**Query**
```sql
 CREATE TABLE sessions
    (
      `session_id` UUID,
      `event_type` SimpleAggregateFunction(groupArrayArray, Array(String))
    )
    ENGINE = AggregatingMergeTree
    ORDER BY (session_id)
```

**To Reproduce**
Create table above, execute:

```sql
SELECT event_type FROM sessions LIMIT 100
```

**Expected behavior**
Column is shown as an array of arrays.

**Comment by bossinc** [comment]
This is not currently supported but I think it makes sense to support AggregateFunction types like arrays of arrays.
