### ISSUE TITLE
Option to add csv format in query for grafana output 

### ISSUE THREAD

**Issue by hackaholic** [grafana/clickhouse-datasource#278]
By default  Grafana append FORMAT JSON to the query, there should be more option format like **csv**

As due to format JSON rendering time of query is increased exponentially , the same query with CSV format dumps results very fast.

The query with **FORMAT JOSN** took 170 sec
**39309** rows in set. **Elapsed: 170.178 sec**. Processed 1.02 million rows, 128.34 MB (**6.00 thousand rows/s**., 754.17 KB/s.)

The same query with **FORMAT CSV** took only 4 sec 
**39309** rows in set. **Elapsed: 4.084 sec**. Processed 1.02 million rows, 128.34 MB (**250.06 thousand rows/s**., 31.42 MB/s.)

Example: From Grafana Query inspector
```
Object
request:Object
url:"api/datasources/proxy/1/?database=pw"
method:"POST"
**data**:"select  * from system.clusters where cluster='iond_shard' FORMAT JSON"     <----------------
hideFromInspector:false
response:Object
```

**Comment by gingerwizard** [comment]
We communicate over FORMAT Native via the go client - the most optimal. There is no use of JSON Format. 
We have no reason to add htis.

**Comment by gingerwizard** [comment]
I don't think this is the datasource plugin @hackaholic @vickyyyyyyy but the monitoring plugin?
