### ISSUE TITLE
Update docs to reflect: Multi-Timeseries only works when the group by value is a string

### ISSUE THREAD

**Issue by austin-barrington** [grafana/clickhouse-datasource#291]
**What happened**:
Multi-Timeseries only works when the group by value is a string when it is an int it is treated as a value. Please see the screenshots below.

The ask: Can you update documentation to reflect this behavior please.

**Incorrect**
![image](https://user-images.githubusercontent.com/31205926/216607899-b85a77a0-b034-4d90-89d4-24040b4ecbf5.png)
Query: `SELECT $__timeInterval(timestamp) as time, profile_id, avg(cpu) FROM default.serverstats WHERE $__timeFilter(timestamp) GROUP BY time, profile_id ORDER BY time ASC`

**Correct**
![image](https://user-images.githubusercontent.com/31205926/216607989-328fa1fc-4f8e-4946-a492-2db8f30fd213.png)
Query: `SELECT $__timeInterval(timestamp) as time, toString(profile_id), avg(cpu) FROM default.serverstats WHERE $__timeFilter(timestamp) GROUP BY time, profile_id ORDER BY time ASC`

**Anything else we need to know?**:

**Environment**:

- Grafana version: 8.5.3
- Plugin version: latest
- OS Grafana is installed on: docker
- User OS & Browser: chrome/windows
- Others:

**Comment by austin-barrington** [comment]
If you agree I'll raise a PR

**Comment by asimpson** [comment]
Hi @austin-barrington 👋 Thanks for reaching out. Let me look into this one and get back to you.

**Comment by bossinc** [comment]
@austin-barrington Are you using the Prepare time series transformation and making the results a multi-frame time series? If so, it says string values are represented as labels. 😃

**Comment by bossinc** [comment]
I am closing this issue. Please reopen if you are still experiencing this problem.
