### ISSUE TITLE
Cannot install dependencies using Node.js v18.x

### ISSUE THREAD

**Issue by slvrtrn** [grafana/clickhouse-datasource#296]
**What happened**:

When building the plugin locally, `yarn` fails on Node.js 18.x since there is no available `eslint-plugin-jsdoc` distribution.

**What you expected to happen**:

Successful installation, cause the main branch of Grafana requires Node.js v18.14.0 now.

**How to reproduce it (as minimally and precisely as possible)**:

* Checkout the project.
* `nvm install 18`
* `nvm use 18`
* `yarn`

**Environment**:

- Plugin version: main branch as of today
- OS Grafana is installed on: Linux (Fedora 37)

**Comment by bossinc** [comment]
We are using `grafana/toolkit@8.5.11`, which depends eventually on `eslint-plugin-jsdoc@37.7.0`. We could upgrade the grafana toolkit to fix this, but we want to continue to support Grafana 8.5 for now. 🙂
