### ISSUE TITLE
Post v1.0

### ISSUE THREAD

**Issue by kirederik** [grafana/clickhouse-datasource#3]
Features to be included after v1.0 

## Features

- [x] #19
- [x] Real time validation of queries on the SQL editor #82
- [x] ~#18~
- [x] Improved error messages
- [x] #29
- [x] #20
- [x] #25

**Comment by gingerwizard** [comment]
@kirederik @scottlepp its very easy to crash the browser at the moment with a large number of datapoints. I'd like to see some form of limit imposed through the LIMIT clause - unless the user overrides i.e. If the user specifies a LIMIT their value is used (even if its greater than the hardcoded limit). If they don't specify a LIMIT we add one. I'd expect us to warn we have applied an upper bound.
