### ISSUE TITLE
Periodic connection loss

### ISSUE THREAD

**Issue by asimpson** [grafana/clickhouse-datasource#320]
**What happened**:
Every day the datasource throws a 500 error that is resolved by re-saving data source settings in Grafana. An error is logged as `rpc error: code = Unavailable desc = error reading from server: EOF`.

**Comment by asimpson** [comment]
One suggestion was to toggle the protocol selection in the config editor. We're waiting to see if that gets rid of the periodic error.

**Comment by Ryado** [comment]
This can be related to ideling in ClickHouse Cloud, wdyt @gingerwizard ?

**Comment by jkaflik** [comment]
@asimpson, this error message `rpc error: code = Unavailable desc = error reading from server: EOF` - isn't it an GRPC error, so Grafana could not talk to plugin process? I think we need to check what happens inside plugin. Is it something you can reproduce?

**Comment by jkaflik** [comment]
@asimpson do you have any updates on this topic?

**Comment by asimpson** [comment]
@jkaflik Unfortunately I was not able to reproduce the issue :disappointed:

**Comment by mshustov** [comment]
let's close until we have a report with more details
