### ISSUE TITLE
Run e2e tests on CI

### ISSUE THREAD

**Issue by mshustov** [grafana/clickhouse-datasource#347]
There are e2e tests https://github.com/grafana/clickhouse-datasource/tree/main/cypress-e2e in the project.
However, CI doesn't run `grafana-e2e run` as a part of frontend testing workflow https://github.com/grafana/clickhouse-datasource/blob/main/.github/workflows/run-frontend-tests.yml

**Comment by asimpson** [comment]
High-level goals with e2e tests:

- [ ] login
- [ ] add datasource
- [ ] add dashboard
- [ ] run hello world sql query
- [ ] remove datasource

**Comment by asimpson** [comment]
We could use docker-compose in CI to manage both clickhouse and grafana?

**Comment by asimpson** [comment]
This issue will be closed in two PRs:

- [ ] https://github.com/grafana/clickhouse-datasource/pull/399
- [ ] PR that runs :point_up: in CI

**Comment by aangelisc** [comment]
Closed by #490
