### ISSUE TITLE
Grafana 10 support

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/clickhouse-datasource#396]
Hello 👋 

Just letting you know that Grafana 10 is coming out soon and your `grafanaDependency` is currently set to not support it. This means customers that will get Grafana 10 will not be able to use your plugin.

You can test your plugin compatibility using the latest Grafana 10 `grafana/grafana-dev` [docker images](https://hub.docker.com/r/grafana/grafana-dev/tags?page=1&name=10.0.0)

https://github.com/grafana/clickhouse-datasource/blob/83b21fb8f62880dfb418d634368ded2f737b766f/src/plugin.json#L62

**Comment by pachico** [comment]
Our Grafana Cloud instances were upgraded this morning and since then, the ClickHouse plugin stopped working.
Please, can you expedite this?
