### ISSUE TITLE
Auto Format does not work

### ISSUE THREAD

**Issue by RoryCrispin** [grafana/clickhouse-datasource#407]
The 'Auto' Format in explore does not pick an appropriate view for the data returned from CH. It just returns ‘Data is missing a number field’ more often than not.

For instance, click 'Explore' on a dashboard panel for a table or logs view and notice that the Format is lost. 
Rather than maintaining the Format of the chart which you clicked 'Explore' on, the format is reset to 'Auto', and the data will fail to show.

This is a bit frustrating when you make a long query and the data returns, but you forgot to set the Format and have to re-run the query.

<img width="616" alt="Screenshot 2023-05-30 at 11 22 10" src="https://github.com/grafana/clickhouse-datasource/assets/716269/da741236-d9ae-41d9-a1ee-e5cee7cbe39e">

**Comment by bossinc** [comment]
@RoryCrispin When I select Explore on a panel, it carries the format to the Explore view. I am using CH 3.1.0 and Grafana 9.5.x. Which version of CH and Grafana are you using?

**Comment by bossinc** [comment]
@RoryCrispin closing issue for now. Feel free to reopen if this is still an issue. 🙂
