### ISSUE TITLE
Editing Ad-hoc filters removes value

### ISSUE THREAD

**Issue by worenga** [grafana/clickhouse-datasource#410]
If you edit an ad-hoc filter, it would be nice to keep the previous value

Before
![image](https://github.com/grafana/clickhouse-datasource/assets/315413/2ef1818f-f0a9-4b4a-aaab-2c2ac880e05e)

When editing

![image](https://github.com/grafana/clickhouse-datasource/assets/315413/afc616cb-a8f9-4e50-affd-1e3b55ef420f)

this is really annoying if you are working with a lot of dashboards with ad-hoc filters on a day-by-day basis. you essentially need to keep to keep editing your queries in a separate editor when you want to amend them to preserve what was entered.

**Comment by bossinc** [comment]
This is an issue with adhoc values in general. I created this issue https://github.com/grafana/grafana/issues/69421 in Grafana for this. :bow:
