### ISSUE TITLE
Plugin health check failed since upgrade to Grafana 10

### ISSUE THREAD

**Issue by jelmokri** [grafana/clickhouse-datasource#438]
Hello,

it seems the plugin is not compatible with Grafana 10.
Since the upgrade, I have the following error  when I save the datasource :
"Plugin health check failed"

Is  there a way to fix without downgrade grafana version ? 

Thanks for your help.

**Comment by mshustov** [comment]
@jelmokri, what plugin version do you use? `v3.1.0` is compatible with v10 https://github.com/grafana/clickhouse-datasource/blob/main/CHANGELOG.md

**Comment by jelmokri** [comment]
Hello, I use the 3.1.0 version of the plugin with grafana 10.0.1

When I save the datasource , I have the error above and so all the panels depending of this datasource not work anymore

**Comment by IsStatic** [comment]
mark,me too

**Comment by aangelisc** [comment]
Hi @jelmokri, @grafana/observability-metrics 
I've tested 3.1.0 against Grafana 10 today and I can successfully connect to a ClickHouse datasource. Do you have any more details on the errors you're seeing?

**Comment by itsmylife** [comment]
@aangelisc I think we (@grafana/observability-metrics) tagged by mistake? Do you need anything specific from our side?

**Comment by aangelisc** [comment]
@itsmylife I'm not sure why you were tagged but yep that's a mistake! Don't worry nothing needed from you 😊

**Comment by jelmokri** [comment]
You can close the issue.

I have fixed it by using full FQDN in Server address  of the datasource configuration

**Comment by mshustov** [comment]
> I have fixed it by using full FQDN in Server address of the datasource configuration

@jelmokri what server address and port did you use before? We can implement a proper validation

**Comment by jelmokri** [comment]
before : server:port
after:    FQDN:port
