### ISSUE TITLE
Improve Documentation/Dashboards v1

### ISSUE THREAD

**Issue by gingerwizard** [grafana/clickhouse-datasource#44]
This ticket captures general improvements to docs required prior to v1 release:

1. Note that for https://github.com/grafana/clickhouse-datasource#multi-line-time-series the order of the fields is important. Ideally this shouldn't be the case but document until its not required.
2. Provide an OOTB dashboard for v1 for monitoring ClickHouse itself + 1 for sample github data. @gingerwizard from ClickHouse to own this.
3. Provide example SQL queries for time chart and multi-series line chart @gingerwizard to own

**Comment by gingerwizard** [comment]
We will include one dashboard with the plugin, focused on Clickhouse monitoring - with a possible redirect to the marketplace.

**Comment by kirederik** [comment]
Closed by #78
