### ISSUE TITLE
Implement Conditional Predicate

### ISSUE THREAD

**Issue by gingerwizard** [grafana/clickhouse-datasource#46]
Per https://github.com/grafana/clickhouse-datasource/issues/18

We need conditionalPredicate, principally for multi-select variables and the All selection. When using a multi-select variable, users have the ability to either rely on using a custom string e.g. `*` or a long comma separated list for the All selection. Neither of these are optimal wrt to performance when used with an IN.

Instead, we can do something like this - assuming a multi-select variable `${repo}` has a custom ALL:

`WHERE if(${repo} == 'ALL', 1, repo_name IN (${repo}))`

This isn't intuitive. Instead, propose we have something similar which only outputs the clause if All isn't selected: 

i.e.

`$conditionalTest(AND toLowerCase(repo_name) IN ($repo),$repo)`

see https://github.com/Vertamedia/clickhouse-grafana#conditional-predicate for similar functionality.

**Comment by bossinc** [comment]
@gingerwizard would there be a time where you would want to list everything when selecting `All` in a where condition? If not, we could find all template variables that have selected `All` and remove the where conditionals that contain these template variables.

**Comment by gingerwizard** [comment]
I cant immediately think of any exampes @bossinc  I would only shy away from search an implementation due to increased complexity and potential for issues. It does, however, represent a more complete solution. I think it depends on your confidence in the enhanced SQL parser.
