### ISSUE TITLE
In the alert rule module,the stat type of query result is transparent

### ISSUE THREAD

**Issue by TyroneMax** [grafana/clickhouse-datasource#464]
![image](https://github.com/grafana/clickhouse-datasource/assets/48749370/443e9854-322f-4dd1-8792-f3512f3d0d5b)

In the alert rule module,i find the stat type of query result is missing. so i wanna inspect the code with the page and i find the color of the result's span is rgb(0,0,0,0). it means text is transparent.
![image](https://github.com/grafana/clickhouse-datasource/assets/48749370/d9209911-b7d6-4b5e-acbd-bc3d6d6d41cc)
when i modify the span's rgb , the text show

grafana version :v9.4.9
clickhouse plugin verison : 3.0.0

**Comment by TyroneMax** [comment]
photo1:
![image](https://github.com/grafana/clickhouse-datasource/assets/48749370/7f059487-435a-426b-b002-3cccd0250218)
photo 2:
![image](https://github.com/grafana/clickhouse-datasource/assets/48749370/d2a0255a-4b70-48ae-b44f-54a9d1bedd71)

**Comment by asimpson** [comment]
Thanks for reporting this, I've added it to our backlog! :trophy:

**Comment by asimpson** [comment]
I'm unable to reproduce this in Grafana v9.5.2 and the ability to toggle a query to stat seems to have been removed in Grafana v10. Please re-open if this issue persists.
