### ISSUE TITLE
Multi-line time-series related support

### ISSUE THREAD

**Issue by heanlan** [grafana/clickhouse-datasource#47]
1. Is there any way we can remove the metric value name from the legend? e.g. "SUM(octetDeltaCount)" in the screenshot below. I'm aware we can give the metric column an alias to make it looks nicer, but it still doesn't make much sense no matter what alias is there. 

What I expect:
sourcePodName -> destinationPodName

What is provided:
SUM(octetDeltaCount) sourcePodName -> destinationPodName

![image](https://user-images.githubusercontent.com/80798942/151235735-73b1182d-e847-44b6-b729-ba0b8a8d0610.png)

2. Shall we expect the support to allow group by multiple columns directly? Instead of concat(col1, col2, ...)

**Comment by scottlepp** [comment]
@heanlan a couple ways I can think of:

- Use variables in the display name:  https://grafana.com/docs/grafana/latest/panels/standard-options/#display-name

  - ${__field.labels}

- "Labels to Fields" Transformation (example below)

![image](https://user-images.githubusercontent.com/6108819/151877978-5490cca2-c9f1-4e89-95e0-4ea27250d07b.png)

![image](https://user-images.githubusercontent.com/6108819/151878086-e6e08673-e611-4f2f-af0e-60f07b17e20f.png)

**Comment by heanlan** [comment]
@scottlepp Thanks a lot. I should make it clearer. I don't want to replace the field with a label. Instead, I want to remove the aggregation field from the legend. 

If the query is:
```sql
select fieldA as time, fieldB, sum(fieldC)
from table
group by time, fieldB
```
The legend should only contain the groupby field - `fieldB`, right? But in the time-series panel, the legend is `sum(fieldC) fieldB`. 

If you check with pie chart, the legend only contains the groupby field, which is desired, and different from time-series.

**Comment by scottlepp** [comment]
@heanlan in my example above the legend only shows the groupby field (machine_group) values.

**Comment by heanlan** [comment]
Can I get some help on why I'm getting this from the query?
The table-view looks normal. 
![image](https://user-images.githubusercontent.com/80798942/152091204-38bb8222-c3ae-4a16-b5ba-04a35630930c.png)
![image](https://user-images.githubusercontent.com/80798942/152091382-e9197842-9693-436d-b261-543fae69181f.png)

**Comment by heanlan** [comment]
More info:
The exact same query worked well on 0.9.7 release. 
![image](https://user-images.githubusercontent.com/80798942/152091651-34430899-7ead-474d-bce8-9b75993e7095.png)

But it doesn't work now:
![image](https://user-images.githubusercontent.com/80798942/152091547-e344b51f-903d-4164-b99f-86bb0137cd46.png)

**Comment by scottlepp** [comment]
Try creating a new panel with the same query.  The json schema changed a bit.  Reminder this is beta and breaking changes may happen.

**Comment by heanlan** [comment]
Thanks. Creating a new panel doesn't seem to work on my side. 

More info:
I found the abnormal behavior only happens when I click on the green triangle button on the top-left corner of the SQL editor. 
![image](https://user-images.githubusercontent.com/80798942/152236073-62d5d3ff-d5e8-4742-bcd3-dbe8bb085558.png)

If I just import the dashboard, and don't edit it, don't click on the green triangle button, it works well. 

In addition, based on my observation, clicking on the blue "Run Query" button doesn't have any effect, no matter on the SQL editor side or Query Builder side, which means it doesn't run the query.
