### ISSUE TITLE
Can't insert COUNT(id) in Field

### ISSUE THREAD

**Issue by duhanov** [grafana/clickhouse-datasource#484]
In last version i cant insert COUNT(id), its translate to "COUNT(id)" and get errror (field not found)
In before version - all ok.

**Comment by SpencerTorres** [comment]
@aangelisc I think this is in the query builder. I'm not sure which input they're referring to, but it seems like they're trying to add `COUNT(id)` as a custom value (perhaps in the column selection). By default, typing a custom column in like this will append it to the SQL as a quoted string ( `"COUNT(id)"` )

A possible fix for this (and other functions) is to remove the quotes when the string contains parenthesis characters `(` `)`

**Comment by SpencerTorres** [comment]
This issue should be fixed in [v4](https://github.com/grafana/clickhouse-datasource/releases). When a column contains a space or parenthesis, we skip the string escape so that it's inserted directly into the query. Open another issue if the problem persists. Thanks!
