### ISSUE TITLE
Unable to add a host with proxy

### ISSUE THREAD

**Issue by naveenpg11** [grafana/clickhouse-datasource#499]
Can we add server address with a path/context appended or is there a way we could do it with custom settings? 
We have our click house deployed behind a proxy, we are unable to create a datasource with our endpoint. 

Endpoint : https://abc.internal.com/clickhouse-proxy/

**Comment by bossinc** [comment]
Do you have the protocol set to HTTP?

**Comment by naveenpg11** [comment]
Yes, I've tried. But not able to make it work. 
basically it is appending the port next to the whole path, ex `{host}/clickhouse-proxy/:{port}` , 
which is also ending up with 
**invalid URL escape \"%2F\"**

**Comment by bossinc** [comment]
Do you have the same problem if you remove the ending `/`? The port being appended shouldn't cause issues unless the port is incorrect. Are you able to connect using the CH CLI when you use your `{host}/clickhouse-proxy/:{port}`?

**Comment by naveenpg11** [comment]
I have not tried it with CH CLI, but the same problem persist, even when i try it without '/'

**Comment by bossinc** [comment]
@naveenpg11 Can you try to connect to CH by some other means? Let's determine if this is a problem with the CH plugin or your connection string. 🙂
