### ISSUE TITLE
Cannot realize Multi-line time series

### ISSUE THREAD

**Issue by Jake0109** [grafana/clickhouse-datasource#503]
**What happened**:
My grafana version is 9.5.0 and my plugin version is 3.3.0.

I want a multi line time series,
my query sql is :
SELECT $__timeInterval(timestamp) as time, log_level, count() as count
FROM okj_log.service 
WHERE $__timeFilter(timestamp) AND hostname IN (${node}) 
GROUP BY log_level, time 
ORDER BY time ASC

and the result is posted as a screen shot.

**What you expected to happen**:
I want it to have multi-line instead of an log_level and count

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**
![image](https://github.com/grafana/clickhouse-datasource/assets/30490184/7883838f-4a0b-43dc-b163-b5e0d0f10c92)

**Anything else we need to know?**:

**Environment**:

- Grafana version:9.5.0
- Plugin version:3.3.0
- OS Grafana is installed on: Amazon linux 2
- User OS & Browser: chrome
- Others:

**Comment by Jake0109** [comment]
I have solved it,
it turns out that log_level is an digit type and after I use multiIf and turn digit type into string type, it can work as expected.
maybe when the value wanted to be group by is a digital type, it may work abnormally.

**Comment by asimpson** [comment]
Glad you got this sorted, I'm going to close this. If the issue persists in a different form or something still isn't quite right feel free to open this back up or file a new  issue.
