### ISSUE TITLE
Query as table

### ISSUE THREAD

**Issue by syco** [grafana/clickhouse-datasource#51]
Hi,
I have a problem with the table visualization when a datetime column is present.

First screenshot, query all values from a clickhouse server, with the clickhouse plugin, table contains a datetime column.
![Screenshot_20220131_153130](https://user-images.githubusercontent.com/54575/151825838-a04245ff-a75c-49a4-a7c6-5b9bc0ff1c26.png)

Second screenshot, query all values from the same server same table, but with the mysql plugin, and select "Format as Table" at the bottom
![Screenshot_20220131_153738](https://user-images.githubusercontent.com/54575/151825867-13ba9afb-1304-4e31-b6f2-64bba91c3fc3.png)

I guess the automatic detection of the timeserie is not taking into account that on the right I have selected the table plugin, and it's creating a json of all columns, when instead it should just return the rows as they are.

Thanks

**Comment by scottlepp** [comment]
@syco can't seem to reproduce.  It should only format as time series if you add a time alias.  What version are you on?

![image](https://user-images.githubusercontent.com/6108819/151881143-bd9cd9fc-ec34-451a-bb8d-71d59682e67d.png)

**Comment by syco** [comment]
I was using Grafana v8.3.4 (a551d74b11) with Clickhouse plugin 0.9.7,
I updated the plugin to 0.9.9 and it's working as expected now.
Thanks
