### ISSUE TITLE
Query builder - issues with Group by when not using Aggregate function

### ISSUE THREAD

**Issue by gingerwizard** [grafana/clickhouse-datasource#54]
The following:

![image](https://user-images.githubusercontent.com/12695796/152021013-bea04335-6b4f-4ebd-ab45-0c28b4616dcf.png)

This produces an invalid query, specifically:

`SELECT count(*) as stars,repo_name,  FROM default.github_events WHERE   ( event_type = 'WatchEvent' ) GROUP BY repo_name ORDER BY count(*) as stars DESC LIMIT 100`

[Executing this query](https://gh-api.clickhouse.tech/play?user=play#ClNFTEVDVCBjb3VudCgqKSBhcyBzdGFycyxyZXBvX25hbWUsICBGUk9NIGRlZmF1bHQuZ2l0aHViX2V2ZW50cyBXSEVSRSAgICggZXZlbnRfdHlwZSA9ICdXYXRjaEV2ZW50JyApIEdST1VQIEJZIHJlcG9fbmFtZSBPUkRFUiBCWSBjb3VudCgqKSBhcyBzdGFycyBERVNDIExJTUlUIDEwMA==) we can see the issue - the excess comma after repo_name.

Removing fixes i.e.

`SELECT count(*) as stars,repo_name FROM default.github_events WHERE   ( event_type = 'WatchEvent' ) GROUP BY repo_name ORDER BY count(*) as stars DESC LIMIT 100`

**Comment by scottlepp** [comment]
@gingerwizard the assumption with the Aggregate option is that you would choose an aggregate, not use the fields to add a custom value with aggregate.  If an aggregate it not chosen, the query is incomplete.

**Comment by gingerwizard** [comment]
@scottlepp that makes sense but when is `Fields` thus relevant? I think that's what confused me in this view i.e. i put my aggregate function there
