### ISSUE TITLE
Query builder - Switching between the query builder and sql editor always looses query 

### ISSUE THREAD

**Issue by gingerwizard** [grafana/clickhouse-datasource#55]
Switching from the query builder to the sql editor correctly warns me that changes will be lost. This seems acceptable for v1.

If i make no changes, however, and switch right back i would expect the builder to be populated. Currently, it is always reset.

**Comment by scottlepp** [comment]
@gingerwizard we will use the ast which will handle basic queries.  We will warn when it's not possible (subqueries, etc).

**Comment by gingerwizard** [comment]
@scottlepp but im building the query in the visual editor. I'm then switching to the sql editor and making zero changes, before returning to the visual editor. I would expect the query to be preserved - if it was valid on initial entry, it should be valid if i return?

Obviously more complex queries developed in the SQL editor will be discarded :+1:
