### ISSUE TITLE
ad-hoc filter does not calculate correct target table 

### ISSUE THREAD

**Issue by mikhno-s** [grafana/clickhouse-datasource#599]
**What happened**:
We added ad hoc filter to one of our dashboards and wanted to filter data on dashboards by clicking `filter` on the table cell of one of the tables in that dashboards.
For example I wanted to filter data by column `level` with value `ERROR`

**What you expected to happen**:
Clicking on the `Filter for value` on the table cell where level is `ERROR` and now expecting that `settings additional_table_filters={'app_logs' : ' level = \'ERROR\' '}` will be added to all queries on this dashboard with this datasource.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a table app logs with some columns and column `level` type String in clickhouse and `timestamp` type DateTime64 with some test data within
- Add this clickhouse as a datasource to grafana
- Create a dashboard and dd a adhoc filter on this datasource
- Create a table visualisation and put some default query into it
```sql
SELECT
*
FROM logs_db.app_logs
WHERE $__timeFilter(timestamp)
LIMIT 10 
```
- Enable `Standard options -> Ad-hoc filterable` in grafana table settings
- Clickhouse `Filter for value` with some value, `ERROR` for example in the table
- Checkout the query in `query inspector`:
```sql
SELECT
*
FROM logs_db.app_logs
WHERE timestamp >= '1700137452' AND timestamp <= '1700141052'
LIMIT 10 settings additional_table_filters={'logs_db' : ' level = \'ERROR\' '}
```

The right query should be 
```sql
SELECT
*
FROM logs_db.app_logs
WHERE timestamp >= '1700137452' AND timestamp <= '1700141052'
LIMIT 10 settings additional_table_filters={'logs_db.app_logs' : ' level = \'ERROR\' '}
```

or `settings additional_table_filters={'app_logs' : ' level = \'ERROR\' '}`

I can suggest that plugin incorrectly gets the table name from the query.

**Environment**:

- Grafana version: 10.1.1
- Plugin version: 3.3.0

**Comment by mikhno-s** [comment]
Hi, @SpencerTorres 
Do you have any ETA for this ?

**Comment by cwurm** [comment]
@mikhno-s @vbichov  I reproduced the problem and opened a PR that will hopefully fix it for you: https://github.com/grafana/clickhouse-datasource/pull/650

**Comment by vbichov** [comment]
the issue wasn't fixed:
it seems that the AST parser is not aware of grafana template variables - this causes it to fail 
![Screenshot 2024-02-19 at 12 28 08](https://github.com/grafana/clickhouse-datasource/assets/4352719/d4696b85-679a-4d84-8d59-cb8a5dbb0ec3)
