### ISSUE TITLE
Can't visualise db data with spaces in JSON Object fields on grafana.

### ISSUE THREAD

**Issue by mallikarjun-12** [grafana/clickhouse-datasource#620]
**What happened**: 
When using the ClickHouse plugin in Grafana to retrieve data from a ClickHouse database, I have encountered issues when dealing with JSON data that contains fields with spaces. The sample JSON data provided is as follows:

```
{
  "timestamp": "2023-12-06 09:20:32",
  "level": "debug",
  "log": {
    "caller": "runtime/asm_arm64.s:1197",
    "cost": 0,
    "count": 0,
    "error": "ws closed: 1001 ",
    "error string": "ws closed: 1001 ",
    "errors": "",
    "id": "IHK9LYy8",
    "index": 0,
    "ip": "",
    "level": "debug",
    "method": "",
    "msg": "error reading client data",
    "path": "",
    "query": "",
    "requestID": "",
    "segment": "",
    "service": "ws",
    "status": 0,
    "statusCode": 0,
    "symbol": "",
    "time": 0,
    "time_taken": 0,
    "ts": "2023-12-06T09:20:32.903Z",
    "user": "",
    "user-agent": "",
    "userID": "",
    "userId": ""
  },
  "service": "ws",
  "msg": "error reading client data",
  "status": 0,
  "requestID": "",
  "ip": "0.0.0.0",
  "method": "",
  "path": "",
  "errors": "",
  "cost": 0
}
```

**Query:** `SELECT "log", "level", "timestamp" FROM "default"."logs" LIMIT 10;`

**Error Field:** `error string`

**Error:** `error querying the database: clickhouse: unsupported column type "string String"`

**What you expected to happen**: 
Visualise data even if the JSON fields have spaces.

**How to reproduce it (as minimally and precisely as possible)**:
- Install Clickhouse plugin
- add click house details and connect
- Insert data into a sample table with one column as JSON which has a field with spaces.
- Try to visualise table data on grafana

**Screenshots**
<img width="1355" alt="Screenshot 2023-12-06 at 3 15 16 PM" src="https://github.com/grafana/clickhouse-datasource/assets/93759119/24303976-c921-4b9d-bf6d-cef49304e404">

**Environment**:

- Grafana version:  10.1.2 (commit: 8e428858dd, branch: HEAD)
- Plugin version: 3.3.0
- OS Grafana is installed on: 6.1.52-71.125.amzn2023.aarch64
- User OS & Browser: Google Chrome
- Others:

**Comment by alyssabull** [comment]
Hey @mallikarjun-12! Is this still an issue? If it is, can you provide us with more information (listed in the comment above)? Thanks!

**Comment by aangelisc** [comment]
Hi @mallikarjun-12, are you able to confirm if this is still an issue? Reading the ClickHouse [docs](https://clickhouse.com/docs/en/sql-reference/data-types/json) I can see that this type is obsolete. Does the `Map` type work instead?

**Comment by aangelisc** [comment]
Thank you for the update @siva-vunet, have you also attempted a similar test with the `Map` type?

@SpencerTorres are you able to chime in here? It seems this may be related to how ClickHouse handles JSON rather than something specific to Grafana.

**Comment by siva-vunet** [comment]
Yes I have tried this with the `Map` data type and it doesn't throw any error there. Have tried with `Array` and `Nested` too just in case and was able to successfully query the rows with spaces in them.

**Comment by SpencerTorres** [comment]
I believe the map type is preferred for now if that works for you. ClickHouse docs say the JSON field is [experimental and obsolete](https://clickhouse.com/docs/en/sql-reference/data-types/json).
