### ISSUE TITLE
Add ability to set `HttpHeaders` via plugin options

### ISSUE THREAD

**Issue by adamyeats** [grafana/clickhouse-datasource#626]
### Discussed in https://github.com/grafana/clickhouse-datasource/discussions/625

<div type='discussions-op-text'>

<sup>Originally posted by **ShravanSunder** December  8, 2023</sup>
I wanted to use this with grafana cloud to view data in cloudflare analytics engine that uses clickhouse.  https://developers.cloudflare.com/analytics/analytics-engine/grafana/

They need use to use authorisation header with https.  How can this be done in this plug in?

If not can we request this feature?</div>

**Comment by SpencerTorres** [comment]
This would be useful. Some questions:

1. Are there any headers we would want to restrict adding? (Hop headers?)
2. Should it be a generic input for an array of headers, or should we just add `Authorization` for now?
3. Would any of these fields need to be stored securely? (Such as `Authorization` containing tokens)

**Comment by ShravanSunder** [comment]
@SpencerTorres this is the link to cloudflare's click house offering which would be great to connect to grafana:  https://developers.cloudflare.com/analytics/analytics-engine/grafana/#grafana-plugin-setup
```
Configure the plugin as follows:

URL: https://api.cloudflare.com/client/v4/accounts/<account_id>/analytics_engine/sql. Replace <account_id> with your 32 character account ID (available in the Cloudflare dashboard).
Leave all auth settings off.
Add a custom header with a name of Authorization and value set to Bearer <token>. Replace <token> with suitable API token string (refer to the [SQL API docs](https://developers.cloudflare.com/analytics/analytics-engine/sql-api/#authentication) for more information on this).
No other options need to be set.
```

**Comment by ShravanSunder** [comment]
@adamyeats Any thoughts on when you would be able to support this.  thanks :)

**Comment by adamyeats** [comment]
@ShravanSunder See https://github.com/grafana/clickhouse-datasource/pull/633

**Comment by SpencerTorres** [comment]
As @adamyeats mentioned, we have a PR open to add this to the v4 branch in #633. v4 will be released soon but if you want to build your own branch asap, I recommend using my `v4-fixes` branch from #666 which includes the latest version of v4 (and includes the http header changes)

**Comment by ShravanSunder** [comment]
@SpencerTorres i'm attempting to use this with grafana cloud, so i'll wait for the PR to be merged :) thanks!

**Comment by SpencerTorres** [comment]
@ShravanSunder Hey! v4 is available now on the plugin catalog if you want to give it a go. I'm gonna close this issue now that the feature is available. Thanks!
