### ISSUE TITLE
Enable Alerting

### ISSUE THREAD

**Issue by nsitarz** [grafana/clickhouse-datasource#63]
Hi All! Thanks for your great work on this plugin! Can we get alerting enabled in `src/plugin.json` so that new alerts may be created for panels using this datasource? I've been using alerts for the past couple days and they seem to work as expected. I can open a PR with the change if you'd like.

**Comment by scottlepp** [comment]
Fixed a8df5c758759094689cccf23a6a4bfa3ed8e75de
