### ISSUE TITLE
Unexpected rollback of changes in SQL Editor

### ISSUE THREAD

**Issue by glushkovds** [grafana/clickhouse-datasource#684]
**What happened**:

In SQL Editor tab, while writing a request, part of what was written is deleted. Moreover, if you press Ctrl + Z after the loss, the loss will return.

**What you expected to happen**:

Everything that is written remains.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add new visualization "Time series" to dashboard
2. Go to SQL Editor tab
3. Expand the editor: click the "plus" icon in the top left corner
4. Type anything
5. Exit the editor by clicking outside the editor
6. Click inside the editor 
7. The text will return to the original

**Screenshots**

![grafana_bug2](https://github.com/grafana/clickhouse-datasource/assets/35626465/26f9ad1b-ee87-4e4b-a43d-0336949f8fea)

**Environment**:

- Grafana version: v10.3.1
- Plugin version: 4.0.2
- OS Grafana is installed on: Docker image "grafana/grafana"
- User OS & Browser: Both Win10 & Ubuntu, both Google Chrome & Mozilla Firefox

**Comment by arniwesth** [comment]
I'm seeing similar issues. When clicking "Run Query" any SQL changes are reverted back. Saving does not seem to solve this either as changes are still reverted even when saving.
