### ISSUE TITLE
Auto detection of timeseries fails to work

### ISSUE THREAD

**Issue by gingerwizard** [grafana/clickhouse-datasource#71]
This uses the internal system.query_log table. This is accessible on the public github instance.

Example query

```
SELECT $__timeInterval(query_start_time) as time,
       any(normalizeQuery(query)) AS normalized_query,
       count() as c
FROM system.query_log
WHERE type != 'QueryStart'
  AND event_date >= today() - 1
  AND event_time >= now() - INTERVAL 1 DAY
  AND normalized_query_hash IN (SELECT normalized_query_hash
                                FROM system.query_log
                                WHERE type in (1, 2, 3, 4)
                                GROUP BY normalized_query_hash
                                ORDER BY count() DESC
                                LIMIT 10)
GROUP BY normalized_query_hash, time
ORDER BY time
LIMIT 1000
```

![image](https://user-images.githubusercontent.com/12695796/153450335-f1c86ed8-275e-493b-9a61-d2e9211f409f.png)

Format in table view looks ok and compliant to reqs.

![image](https://user-images.githubusercontent.com/12695796/153450491-1678822e-70bd-448a-9be9-9ea312708118.png)

Adding a multi-frame transform fixes it

![image](https://user-images.githubusercontent.com/12695796/153450632-03c67318-7b0e-4251-8b59-48145fa167be.png)

**Comment by scottlepp** [comment]
@bossinc looks like the AST isn't parsing the fields correctly.  There are multiple items selected here but the ast only has one item.  Also, need to remove carriage return characters.

![image](https://user-images.githubusercontent.com/6108819/153456511-28f1e46e-9424-4f19-b032-a8b98cca8fee.png)
