### ISSUE TITLE
Clickhouse cpu, memory, and connection are growing abnormally

### ISSUE THREAD

**Issue by gfes980615** [grafana/clickhouse-datasource#713]
**What happened**:
We found the number of ClickHouse connections, CPU, and memory will be increased too higher when we upgraded the Datasource version from 3.3.0 to 4.0.2

We have nearly 2000 queries per 1 min
When we use version 3.3.0 the metrics are normal, but in version 4.0.2 these metrics seems unusual growth.

**What you expected to happen**:
The Clickhouse resource usage will be the same 

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade the version from 3.3.0 to 4.0.2

**Screenshots**

Clickhouse 3.3.0 metrics:
<img width="1438" alt="Screenshot 2024-02-19 at 15 35 46" src="https://github.com/grafana/clickhouse-datasource/assets/25905125/252b4e1f-7f27-48e5-a8d1-1622469af445">
<img width="1439" alt="image" src="https://github.com/grafana/clickhouse-datasource/assets/25905125/913b8bfa-ecef-4fd1-9b78-07f927d89559">

Clickhouse 4.0.2 metrics:
<img width="1440" alt="image" src="https://github.com/grafana/clickhouse-datasource/assets/25905125/83c74323-a013-40e7-95da-9a0c689df535">
<img width="1440" alt="image" src="https://github.com/grafana/clickhouse-datasource/assets/25905125/e12d031e-930b-4a04-9e9d-7aedde544425">

**Anything else we need to know?**:

**Environment**:

- Grafana version: 9.5.15
- Plugin version: 4.0.2
- OS Grafana is installed on: Alpine Linux
- User OS & Browser: Google Chrome
- Others: n/a

**Comment by mshustov** [comment]
@gfes980615 could you check the number of queries in ClickHouse [query_log](https://clickhouse.com/docs/en/operations/system-tables/query_log) before and after the upgrade? Do you see any anomalies? Feel free to contact me on [ClickHouse public Slack](https://clickhouse.com/slack) to investigate the problem deeper

**Comment by gfes980615** [comment]
Hi, @mshustov 

Here is our origin query in Grafana:
```sql
select dt, error / total as error_rate_5xx
from (
  Select dt, sum(value) as total, SUM( CASE WHEN "http_status_code" like '4%' THEN value ELSE 0 END) as error
  from dist_otel_ubt_table
  where 1=1 and 
  customer_id = 'f25a4fcc-f918-4ea0-aede-5dd1717748d0'
  and service_name = 'prod_v1_svp_gateway_aws_us-east-1_Commercial'
  and cpid = 'aak' 
  and $__timeFilter(toUnixTimestamp(dt))
  group by dt order by dt
)
```

In our case, it seems `toUnixTimestamp`function makes this situation happen, when I remove this function, all metrics seem normal

However, when I checked the query_log between 3.3.0 and 4.0.2, I found the difference between them.

In version 4.0.2:
```sql
select dt, error / total as error_rate_5xx from (
    Select dt, sum(value) as total, SUM( CASE WHEN "http_status_code" like '4%' THEN value ELSE 0 END ) as error
    from dist_otel_ubt_table
    where 1=1 and
    customer_id = 'f25a4fcc-f918-4ea0-aede-5dd1717748d0' and
    service_name = 'prod_v1_svp_gateway_aws_us-east-1_Commercial' and
    cpid = 'aak' and
    toUnixTimestamp(dt) >= toDateTime64(1708408871359/1000, 3) AND
    toUnixTimestamp(dt) <= toDateTime64(1708412471359/1000, 3)
    group by dt order by dt
)

10 rows in set. Elapsed: 1.964 sec. Processed 4.20 million rows, 255.38 MB (2.14 million rows/s., 130.03 MB/s.)
Peak memory usage: 7.20 MiB.
```

Modify `$__timeFilter(toUnixTimestamp(dt))` to `$__timeFilter(dt)` will get:
```sql
select dt, error / total as error_rate_5xx from (
    Select dt, sum(value) as total, SUM( CASE WHEN "http_status_code" like '4%' THEN value ELSE 0 END ) as error
    from dist_otel_ubt_table
    where 1=1 and
    customer_id = 'f25a4fcc-f918-4ea0-aede-5dd1717748d0' and
    service_name = 'prod_v1_svp_gateway_aws_us-east-1_Commercial' and
    cpid = 'aak' and
    dt >= toDateTime64(1708408871359/1000, 3) AND
    dt <= toDateTime64(1708412471359/1000, 3)
    group by dt order by dt
)

10 rows in set. Elapsed: 0.021 sec. Processed 162.66 thousand rows, 12.45 MB (7.67 million rows/s., 587.04 MB/s.)
Peak memory usage: 6.15 MiB.
```

---

In version 3.3.0, this situation will not happen.

```sql
select dt, error / total as error_rate_5xx from (
    Select dt, sum(value) as total, SUM( CASE WHEN "http_status_code" like '4%' THEN value ELSE 0 END ) as error
    from dist_otel_ubt_table
    where 1=1 and
    customer_id = 'f25a4fcc-f918-4ea0-aede-5dd1717748d0' and
    service_name = 'prod_v1_svp_gateway_aws_us-east-1_Commercial' and
    cpid = 'aak' and
    toUnixTimestamp(dt) >= '1708408871' AND toUnixTimestamp(dt) <= '1708412471'
    group by dt order by dt
)

10 rows in set. Elapsed: 0.017 sec. Processed 90.11 thousand rows, 8.10 MB (5.40 million rows/s., 485.02 MB/s.)
Peak memory usage: 3.60 MiB.
```
```sql 
select dt, error / total as error_rate_5xx from (
    Select dt, sum(value) as total, SUM( CASE WHEN "http_status_code" like '4%' THEN value ELSE 0 END ) as error
    from dist_otel_ubt_table
    where 1=1 and
    customer_id = 'f25a4fcc-f918-4ea0-aede-5dd1717748d0' and
    service_name = 'prod_v1_svp_gateway_aws_us-east-1_Commercial' and
    cpid = 'aak'
    and dt >= '1708408871' AND dt <= '1708412471'
    group by dt order by dt
)
 
10 rows in set. Elapsed: 0.018 sec. Processed 90.11 thousand rows, 8.10 MB (4.97 million rows/s., 446.68 MB/s.)
Peak memory usage: 3.60 MiB.
```

Here are the other two questions:
1. In our case, we use OTEL collector to ingest data to clickhouse. Should we modify the tracing table DDL from `toUnixTimestamp(Timestamp)` to `Timestamp` better?
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/exporter_traces.go#L197
2. Or if there is another method that can let us transfer the `$__timeFilter` like version 3.3.0

related: #699
