### ISSUE TITLE
Editing Clickhouse query in extended view of SQL Editor is resetting the query

### ISSUE THREAD

**Issue by edin008** [grafana/clickhouse-datasource#729]
**What happened**:
This only happens with Clickhouse data source while SQL Editor is extended.
Anything edited in extended view of SQL Editor will be resetted to the latest/default state of query.

**What you expected to happen**:
No problems with writing query in extended view (+ option).

**How to reproduce it (as minimally and precisely as possible)**:
1. Write simple query in non extended view (+ should be visible).
![image](https://github.com/grafana/clickhouse-datasource/assets/66313770/4c08fe83-721f-4c6b-9ea2-06ef4047615f)

2. Extend the view (- should be visible) and make some changes to the query. Break some lines and add where clause.
![image](https://github.com/grafana/clickhouse-datasource/assets/66313770/c1c01b7c-4151-47b4-aaa5-5c0ef65d1e9c)
Do some clicking around, run the query and some more clicking.
After a very short time the query will reset to latest/default state of query that was in non extended view.
![image](https://github.com/grafana/clickhouse-datasource/assets/66313770/5cd2390a-fdb5-4e49-ba9d-bb07a13f65ef)

Attaching GIF as well.
First there is query in non extended view (visible +).
Then I switch to extended view (visible -), problem of query resets is visible here.
Then I switch back to non extended view (visible +), no problems here.
Then I switch again back to extended view (visible -) and problem of query reset is visible again.

![grafana_clickhouse_bug](https://github.com/grafana/clickhouse-datasource/assets/66313770/0cd99bfd-0d61-496f-bbeb-2ae7da7058f4)

**Screenshots**

**Anything else we need to know?**:

**Environment**:

- Grafana version: Tested on 10.3.3, 10.2.4, 10.1.7
- Plugin version: 4.0.2
- OS Grafana is installed on: Debian
- User OS & Browser: Windows, Chrome (Tested also on Firefox)
- Others: /

**Comment by SpencerTorres** [comment]
Hello! Thank you for the detailed report.

This has been reported in #684 and fixed in #687, pending release
