### ISSUE TITLE
Disordering from rawQuery to rawSql in 0.9.12/0.9.13

### ISSUE THREAD

**Issue by heanlan** [grafana/clickhouse-datasource#73]
The issue does not appear in releases before 0.9.12. 
`[AND flowType IN (1,2)
AND sourcePodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')]()`
↓
`[FROM flows_pod_view WHERE 2) AND flowType IN (1, sourcePodNamespace NOT IN ('kube-system', 'flow-visibility', 'flow-aggregator')]()`
![image](https://user-images.githubusercontent.com/80798942/153482103-4d2fa571-d337-4454-a5fc-e72e583a91dc.png)

**Comment by heanlan** [comment]
They are being synced. They have the same content. 

I think I found the issue, seems to be parsing issue. 
When the WHERE clause is `AND flowType IN (1,2)`, it will fail; 
when adding a space between 1 and 2 -> `AND flowType IN (1, 2)`, it works.

**Comment by scottlepp** [comment]
@bossinc AST issue?
