### ISSUE TITLE
Plugin 4.0.2 breaks my segmentation time series and makes my query difficult to update

### ISSUE THREAD

**Issue by bmanth60** [grafana/clickhouse-datasource#738]
**What happened**:
When updating queries from the 3.3.0 plugin to 4.0.2, the group by segments are not working. This is because the editor view no longer includes the format option.

As a workaround, I need to remove my custom query, switch to the builder, select the query type as time series then re-add my custom query.

**What you expected to happen**:
Either one of two options:
- My query in the editor should be able to update the query type
- OR my queries in my panels when the time series visualization is selected should always work

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a new panel
2. Select editor
3. Write a query with segmentation using group by

**Screenshots**
<img width="1072" alt="image" src="https://github.com/grafana/clickhouse-datasource/assets/5578150/0f57f7e4-cb82-4d19-9440-92006591908f">

**Anything else we need to know?**:

**Environment**:

- Grafana version: 10.2.1
- Plugin version: 4.0.2
- OS Grafana is installed on: docker
- User OS & Browser: OSX Sonoma 14.3.1 & Chrome
- Others:

**Comment by SpencerTorres** [comment]
Hey! Thanks for submitting an issue.

This is the same problem as #730, fixed in #734. Hope to have it available soon for you to use.

Thanks!
