### ISSUE TITLE
timeInterval macro

### ISSUE THREAD

**Issue by heanlan** [grafana/clickhouse-datasource#76]
I'm not sure how to use it. I selected 60s as the time interval, while still get multiple records within 60s. 
![image](https://user-images.githubusercontent.com/80798942/153527027-a62b3596-75d3-4a59-ad64-fb4343b58745.png)

**Comment by scottlepp** [comment]
Can you show the query please.  Also when creating an issue please provide Grafana and Plugin versions.

**Comment by heanlan** [comment]
Please ignore the last screenshot. 

Grafana v8.3.3 
Plugin v0.12.0

```sql
SELECT flowEndSeconds as time, destinationPodName, SUM(throughput)
FROM flows_pod_view
WHERE $__timeFilter(flowEndSeconds)
AND destinationPodName == 'web-server-1-d89f495cb-h4ncn'
AND $__timeInterval(flowEndSeconds)
GROUP BY time, destinationPodName
ORDER BY time
```
Getting: 
`code: 43, message: Illegal type (DateTime('UTC')) of 4 argument of function and: error querying the database`

![image](https://user-images.githubusercontent.com/80798942/153650049-1fb423f3-2329-4ee2-a825-4ff944a0ba56.png)

The data type of column `flowEndSeconds` is time.time. It works well with `$__timeFilter(flowEndSeconds)`, while gets error with `$__timeInterval(flowEndSeconds)`. What is the required datatype as an argument of `$__timeInterval`? 

![image](https://user-images.githubusercontent.com/80798942/153653387-23db5f0d-94e0-4dea-8cda-b3beb3c30db5.png)

**Comment by scottlepp** [comment]
$__timeInterval is not a filter.  You should use it in your select, not the where clause.

```
SELECT $__timeInterval(flowEndSeconds) as time...
```

**Comment by heanlan** [comment]
Thanks! It works.
