### ISSUE TITLE
custom trace table prefix does not work on grafana tracing

### ISSUE THREAD

**Issue by cezhang** [grafana/clickhouse-datasource#762]
**What happened**:
![image](https://github.com/grafana/clickhouse-datasource/assets/5362164/8903b006-dc60-4ba3-9b67-b91aa3ddc488)
My trace table is naming as `o11y_traces`, BUT xx_traces_trace_id_ts table is hardcoded as `otel` and no way to config that, making query not working (BTW, it's ok to use sql builder to change that manually, but it's stupid.)
**What you expected to happen**:
Make xx_traces_trace_id_ts configurable or induce that correctly based on trace table
**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:

- Grafana version:
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by SpencerTorres** [comment]
Same issue as #761, follow that thread for updates on this topic
