### ISSUE TITLE
Regression in `LowCardinality(Nullable(String))` type processing in v4.0.5

### ISSUE THREAD

**Issue by btmc** [grafana/clickhouse-datasource#805]
**What happened**:

Trying to select a column of aforementioned type returns an error:

```
sql: Scan error on column index 0, name "%column_name%": unsupported Scan, storing driver.Value type *string into type *string: Could not process SQL results

```

It seems to be a regression of [#785](https://github.com/grafana/clickhouse-datasource/pull/785), wherein the regexp for `"Nullable(String)"` Converter [has been changed](https://github.com/grafana/clickhouse-datasource/pull/785/commits/310eeaed1cafcecffc3cf088aea40d6338a01a07#diff-ee17992c987df01645f07024591cfd9212594ea65f8d7f7a06446d49523fa7d5L37) to match on the beginning of string only, thus not matching `LowCardinality(Nullable(String))` anymore (and in this case default Converter is used and that is probably the cause of the error).

I've downgraded datasource version to **v4.0.4** to corroborate that and the error indeed disappeared.

<br>

**What you expected to happen**:

No errors.

<br>

**How to reproduce it (as minimally and precisely as possible)**:

In Explore view:

```
select
    toNullable('test')
;
```

OK

```
select
    toLowCardinality('test')
;
```

OK

```
select
    toLowCardinality(
        toNullable('test'))
;
```

Error:

```
sql: Scan error on column index 0, name "toLowCardinality(toNullable('test'))": unsupported Scan, storing driver.Value type *string into type *string: Could not process SQL results
```

<br>

**Environment**:

v4.0.6, grafana v10.4.1

**Comment by adamyeats** [comment]
@SpencerTorres As you were involved in the PR that @btmc linked to above, would you be able to comment on this? As they rightly point out, `^` matches the start of string, meaning that nesting within `LowCardinality()` would indeed break after this PR was merged.
