### ISSUE TITLE
Span status code not indicating as error in the trace UI

### ISSUE THREAD

**Issue by nextrevision** [grafana/clickhouse-datasource#809]
**What happened**:

I'm using the latest version of the OpenTelemetry Clickhouse Exporter and have it integrated with Grafana 10.x using the latest Clickhouse datasource version. I can view the trace, but the error icon/indicator does not appear.

**What you expected to happen**:

When viewing a trace with spans that are of `STATUS_CODE_ERROR`, I would expect a visual hint.

**How to reproduce it (as minimally and precisely as possible)**:

I think what is missing is a SpanAttribute named `error` being explicitly set. Since OpenTelemetry doesn't appear to support `error` as a SpanAttribute through their SDKs, would it be better to key off of the StatusCode column directly? 

**Screenshots**

Below without the indicator:

<img width="1672" alt="Screenshot 2024-04-22 at 3 15 00 PM" src="https://github.com/grafana/clickhouse-datasource/assets/2991219/aba597d9-6b40-4d5c-acab-45c42d655db3">

A query showing the result:

```
SELECT StatusCode
FROM otel_traces
WHERE SpanId = 'e13714f30858326c'

Query id: 13342227-f21a-4196-8a1b-d970b7211ce5

   ┌─StatusCode────────┐
1. │ STATUS_CODE_ERROR │
   └───────────────────┘

1 row in set.
```

**Environment**:

- Grafana version: 10.4.1
- Plugin version: Clickhouse 4.0.6
- OS Grafana is installed on: Linux/Docker
- User OS & Browser: Firefox
- Others:

**Comment by SpencerTorres** [comment]
The trace panel requires a specific column name to be returned, usually with a specific data type.

This structure is defined here: https://grafana.com/docs/grafana/latest/explore/trace-integration/#data-api

You can try writing a query that shows the status you want. If you have any suggestions on how to do this consistently from one of the other columns (such as `StatusCode` or `Severity*`), let me know and we could look into adding it.

Thanks!

**Comment by aangelisc** [comment]
Hi @nextrevision, I'm closing this as based on the comment from @SpencerTorres above this should have a workaround to provide the correct data schema. Please re-open if this is still a problem for you!

**Comment by nextrevision** [comment]
I'm not sure this is something that should be solved outside of the plugin, mainly because the plugin requires the opentelemetry clickhouse exporter to function. I am using the exporter with no modifications. I think the since clickhouse datasource plugin requires the otel exporter, it should add support for displaying errors that are builtin to the schema.

**Comment by heejew** [comment]
> This structure is defined here: https://grafana.com/docs/grafana/latest/explore/trace-integration/#data-api

I'm sorry, but where is the structure described? How do I know what field names and types the plugin expects for full display? 
There is nothing on the specified page, only http.
