### ISSUE TITLE
Alerts Section --> Query Builer --> Filter dropdown doesn't work . Not able to change "IS NOT NULL"

### ISSUE THREAD

**Issue by Guille-vn** [grafana/clickhouse-datasource#828]
**What happened**:

Dropdown are broken

**What you expected to happen**:

Dropdown filter works

**How to reproduce it (as minimally and precisely as possible)**:

1) Go to the Alerts Section  
2) Open Query Builer  
3) Add a new Filter and select a Field
4) Tryi to change "IS NOT NULL" or "IS ANYTHING" to another option 

![image](https://github.com/grafana/grafana/assets/162587937/d54cdf7b-b715-4a85-9fca-109d175ec3c7)

It should change and give the posibility to configure the filter
It's happens using a ClickHouse Datasource.

**Comment by SpencerTorres** [comment]
Interesting, it looks like the dropdown appears but a new option isn't selected. This is likely something with the state management of the plugin/query. I haven't tested the query builder on this page before so there's likely some differences with this vs the explore/dashboard views.
