### ISSUE TITLE
IN operator not correctly constructed in Query Builder Filter

### ISSUE THREAD

**Issue by ryn9** [grafana/clickhouse-datasource#830]
**What happened**:
When constructing a query using Query Builder, if using the 'IN' operator for a filter, the generated SQL is not correct

**What you expected to happen**:
the generated SQL for XXX IN (1,2,3) would be expected to be
XXX IN (1,2,3)
Instead it produces 
XXX IN '(1,2,3)'

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to Query Builder, Query Type: Time Series
2. Create a Filter using the 'IN' operator
3. View the generated SQL Preview

**Anything else we need to know?**:
n/a

**Environment**:

- Grafana version:
- Plugin version: grafana-clickhouse-datasource v4.0.7
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by Guille-vn** [comment]
I reported something similar . It's seems like "Clickhouse" connector is not working well

**Comment by ryn9** [comment]
@Guille-vn do you have a link to your issue?
The data source plugin has actually been working quite well in my tests, but like anything, there are some bugs.

**Comment by Guille-vn** [comment]
> @Guille-vn do you have a link to your issue? The data source plugin has actually been working quite well in my tests, but like anything, there are some bugs.

Sure

https://github.com/grafana/grafana/issues/87573
https://github.com/grafana/clickhouse-datasource/issues/828

**Comment by Kenterfie** [comment]
We are currently using version 4.0.8 and still have the same problem. When I use the IN operator for ad hoc filters, it still outputs '(1,2,3)' instead of (1,2,3). We switched our dashboards from Altinity to this one a few weeks ago and didn't have similar issues before. I suspect the problem was only solved for a part of the plugin and not in general.
