### ISSUE TITLE
unsupported value: +Inf

### ISSUE THREAD

**Issue by simPod** [grafana/clickhouse-datasource#853]
**What happened**:

> json: unsupported value: +Inf: Could not process SQL results

**What you expected to happen**:

success

**How to reproduce it (as minimally and precisely as possible)**:

```sql
SELECT t, arrayMap(a -> (a.1, a.2/runningDifference( t/1000 )), groupArr)
FROM (
    SELECT t, groupArray((query, c)) AS groupArr FROM (
        SELECT (intDiv(toUInt32(event_time), 4) * 4) * 1000 AS t, substring(query, 1, 45) AS query, count() c FROM system.query_log
        WHERE $__timeFilter(event_time) AND
            cityHash64(query) global in (
                SELECT cityHash64(substring(query,  1,  45)) AS h
                FROM system.query_log
                WHERE $__timeFilter(event_time)
                    AND type in ($type)
                    -- AND initial_user in ('', $user)
                    AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))
                GROUP BY h
                ORDER BY count() desc
                LIMIT 20
            )
            AND type in ($type)
            -- AND initial_user in ()
            AND('$query_type' = 'all' or(positionCaseInsensitive(query,  '$query_type') = 1))
        GROUP BY event_time, query
    )
    GROUP BY t ORDER BY t
) LIMIT 1
```

**Screenshots**

**Anything else we need to know?**:

**Environment**:

- Grafana version: Grafana v10.4.3 (6e6fbf6a34)
- Plugin version: 4.0.7
- OS Grafana is installed on: ubuntu
- User OS & Browser: chrome
- Others:

**Comment by adamyeats** [comment]
Hey @simPod thanks for reporting this! I think this might possibly be something to do with the query itself.

If I'm not mistaken, looking at the first line of your query, `runningDifference(t / 1000)` computes the difference between the current and the previous value of `t / 1000`. If two consecutive values of `t` are the same, `runningDifference(t / 1000)` will return `0`, leading to a division by zero and then (I think!), a `+Inf`. Is that a possibility?

The `json: unsupported value: +Inf` error message would be expected in that case as `json.Marshal` is unable to parse those values.

**Comment by simPod** [comment]
Yes, I though it might be something with the query itself. But the plugin should give user maybe more verbose message?

**Comment by SpencerTorres** [comment]
This is actually one of the more helpful error messages I've seen from the plugin, not sure if we can get any more specific than that since errors can be caused by so many things in the query.

I do still want to improve the errors seen on the query editor, but this one makes sense.

Perhaps we could avoid the error by setting the value to some reasonable value, either `max_int` or `0`, but I wouldn't want to manipulate the response like that

**Comment by adamyeats** [comment]
> Perhaps we could avoid the error by setting the value to some reasonable value, either max_int or 0, but I wouldn't want to manipulate the response like that

This is something we can definitely put on the backlog for future consideration. 👍

**Comment by simPod** [comment]
Don't bother with it much. Thanks. Close at will.
