### ISSUE TITLE
Imprecise trace representation

### ISSUE THREAD

**Issue by NicolasBissig** [grafana/clickhouse-datasource#888]
**What happened**: When viewing an OpenTelemetry Trace stored in ClickHouse, the trace is displayed with wrong timing information

![Pasted image 20240619151413](https://github.com/grafana/clickhouse-datasource/assets/21075964/2a132bd9-4b98-4b9a-b06d-56365a14db09)
*Figure 1: The ClickHouse trace viewed in grafana*

![Pasted image 20240619151429](https://github.com/grafana/clickhouse-datasource/assets/21075964/4190f82e-c37f-4047-8e57-7bd82a30bd1b)
*Figure 2: The same trace stored and queried from Tempo viewed in Grafana*

The durations of the spans are correct, however the starting positions are not. The tempo trace is correct here.

**What you expected to happen**: I expect the ClickHouse trace representation to be the correct one.

**How to reproduce it (as minimally and precisely as possible)**: Setup any tracing solution and configure an OpenTelemetry collector to export the data at the same time to the ClickHouse database AND a Tempo Backend. View the same trace in both systems. Use the ClickHouse exporter contained in the contrib version of the collector.

**Screenshots**

**Anything else we need to know?**: This seems to relate to https://github.com/grafana/clickhouse-datasource/issues/771

This is the default query produced for viewing a trace:

```sql
WITH 'd469af085bf7524ba4dd5eb2814a6918' as trace_id, (SELECT min(Start)  
                                                      FROM "otel"."otel_traces_trace_id_ts"  
                                                      WHERE TraceId = trace_id) as trace_start, (SELECT max(End) + 1  
                                                                                                 FROM "otel"."otel_traces_trace_id_ts"  
                                                                                                 WHERE TraceId = trace_id) as trace_end  
SELECT "TraceId"                                                                                           as traceID,  
       "SpanId"                                                                                            as spanID,  
       "ParentSpanId"                                                                                      as parentSpanID,  
       "ServiceName"                                                                                       as serviceName,  
       "SpanName"                                                                                          as operationName,  
       "Timestamp"                                                                                         as startTime,  
       multiply("Duration", 0.000001)                                                                      as duration,  
       arrayMap(key -> map('key', key, 'value', "SpanAttributes"[key]), mapKeys("SpanAttributes"))         as tags,  
       arrayMap(key -> map('key', key, 'value', "ResourceAttributes"[key]),  
                mapKeys("ResourceAttributes"))                                                             as serviceTags  
FROM "otel"."otel_traces"  
WHERE traceID = trace_id  
  AND startTime >= trace_start  
  AND startTime <= trace_end  
LIMIT 1000
```
If it is adapted to 

```sql
WITH 'd469af085bf7524ba4dd5eb2814a6918' as trace_id, (SELECT min(Start)  
                                                      FROM "otel"."otel_traces_trace_id_ts"  
                                                      WHERE TraceId = trace_id) as trace_start, (SELECT max(End) + 1  
                                                                                                 FROM "otel"."otel_traces_trace_id_ts"  
                                                                                                 WHERE TraceId = trace_id) as trace_end  
SELECT "TraceId"                                                                                   as traceID,  
       "SpanId"                                                                                    as spanID,  
       "ParentSpanId"                                                                              as parentSpanID,  
       "ServiceName"                                                                               as serviceName,  
       "SpanName"                                                                                  as operationName,  
       "Timestamp"                                                                                 as startTimeNormal,  
       toUnixTimestamp64Nano(Timestamp) / 1000000                                                  as startTime,  
       multiply("Duration", 0.000001)                                                              as duration,  
       arrayMap(key -> map('key', key, 'value', "SpanAttributes"[key]), mapKeys("SpanAttributes")) as tags,  
       arrayMap(key -> map('key', key, 'value', "ResourceAttributes"[key]),  
                mapKeys("ResourceAttributes"))                                                     as serviceTags  
FROM "otel"."otel_traces"  
WHERE traceID = trace_id  
  AND startTimeNormal >= trace_start  
  AND startTimeNormal <= trace_end  
LIMIT 1000
```
mainly with `toUnixTimestamp64Nano(Timestamp) / 1000000 as startTime` will result in the correct trace representation:

![Pasted image 20240619151547](https://github.com/grafana/clickhouse-datasource/assets/21075964/54f254da-9dbd-46c4-b8d5-65b99f1b35cf)
*Figure 3: Trace view from ClickHouse with adapted query, now displayed correctly.*

**This is just a workaround / solution suggestion, if there are better ways to provide the same result, please let me know**

**Environment**:

- Grafana version: 11
- Plugin version: 4.1.0
- OS Grafana is installed on: Docker or Kubernetes
- User OS & Browser: Linux / Windows & Brave Browser
- Others:

**Comment by SpencerTorres** [comment]
It seems like Grafana prefers the `float` timestamps for tracing purposes since JavaScript `Date` can't go sub-millisecond.

We will need to do a similar formula to what we do for duration, but this should be an easy change.

@aangelisc changing duration unit only affects duration for now,  but now I see we might need to apply it to startTime as a `float`

**Comment by aangelisc** [comment]
Thanks for the response @SpencerTorres, perhaps we could generalise [this](https://github.com/grafana/clickhouse-datasource/blob/d6067905fbea0f1dae92584a010fdf5173e72773/src/data/sqlGenerator.ts#L561) to handle any column appropriately, wdyt?

**Comment by SpencerTorres** [comment]
I think it could be a constant function actually, since we would know the precision from the query.

That function is used for when we don't know the intended scale of `duration`, but if we're the ones converting the `startTime` then we can always go straight to nanoseconds and then shift the decimal to milliseconds.

Should be an easy change. See #720 for a visualization of this issue occurring on `duration`

**Comment by NicolasBissig** [comment]
@aangelisc as I see that there already is an open pull request, can I assume that the question with the duration unit has been answered? :)

**Comment by aangelisc** [comment]
Hi @NicolasBissig, yep that question has been answered. I believe the open PR should fix this problem!

**Comment by NicolasBissig** [comment]
Cool, thanks for the fast fix guys! :clap:
