### ISSUE TITLE
Trace Detail no Longer Works

### ISSUE THREAD

**Issue by forestsword** [grafana/clickhouse-datasource#900]
Hello, after the recent update the trace detail has stopped working. I'm using the latest grafana and this plugin.

After I click on a trace to show it from the trace id list nothing is returned. The multiply function added in https://github.com/grafana/clickhouse-datasource/pull/890 I think was not fully implemented, the [`trace_start` and `trace_end` ](https://github.com/grafana/clickhouse-datasource/blob/13014f723e4ba27cb1566f06d21e7ce7a2b524d2/src/data/sqlGenerator.ts#L158-L159) also need the function added in order for the where comparison to work. Manually adding them to the generated SQL I get the trace returned.

**Comment by SpencerTorres** [comment]
Looking into this, thanks for the info

**Comment by aangelisc** [comment]
Fixed by #890 😊

**Comment by forestsword** [comment]
Thanks! Could we have a patch release of the plugin?

**Comment by NicolasBissig** [comment]
@SpencerTorres @aangelisc When is this planned to be released?
