### ISSUE TITLE
Error Importing 'Simple ClickHouse OTel Dashboard' - Dashboard Not Found

### ISSUE THREAD

**Issue by rudebono** [grafana/clickhouse-datasource#908]
**What happened**:

I have successfully added ClickHouse as a datasource in Grafana Cloud.
However, when I tried to import the default dashboard titled `Simple ClickHouse OTel Dashboard`,
I encountered an error stating "Dashboard not found."

**What you expected to happen**:

The dashboard should be imported successfully without any errors.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add ClickHouse as a datasource in Grafana.
2. Attempt to import the "Simple ClickHouse OTel Dashboard".

**Screenshots**

<img width="1442" alt="스크린샷 2024-07-17 오후 6 06 28" src="https://github.com/user-attachments/assets/4e2ccc37-0075-42e2-bd49-25a9e0bc1a77">

**Environment**:

- Grafana version: 11.2.0-73179
- Plugin version: 4.3.0
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Apple M1 / macOS sonoma 14.5 & Google Chrome 126.0.6478.114
- Others:

**Comment by aangelisc** [comment]
Hi @rudebono, thank you for raising this! I have a fix up in #919 😊

**Comment by rudebono** [comment]
> Hi @rudebono, thank you for raising this! I have a fix up in #919 😊

Thank you so much! 😘
