### ISSUE TITLE
Inject time filter into timeseries query builder

### ISSUE THREAD

**Issue by gingerwizard** [grafana/clickhouse-datasource#95]
**Is your feature request related to a problem? Please describe.**

If i build a query using the timeseries mode, a `$__timeInterval` function is used automatically. This is good as it ensures the bucket size reflects the time window. However, the time window itself is not restricted e.g.

![image](https://user-images.githubusercontent.com/12695796/155563266-a3eb3bde-4398-414b-aa53-417ee189e1a3.png)

Notice the query

`SELECT $__timeInterval(EventTime), CookieEnable, count() count FROM yandex.hits GROUP BY CookieEnable, EventTime ORDER BY EventTime ASC`

The user has specified a time field so a WHERE clause could be added here automatically e.g.

SELECT $__timeInterval(EventTime), CookieEnable, count() count FROM yandex.hits WHERE $__timefilter(EventTime) GROUP BY CookieEnable, EventTime ORDER BY EventTime ASC`

Without this the number of data points can be very large, crashing the browser.

**Describe the solution you'd like**

Auto inject `__$timefilter` in the WHERE clause.

**Describe alternatives you've considered**

Allowing the user to use the expression in the filter.

**Comment by scottlepp** [comment]
Fixed by #96
